---
title: "PhD Advancement Reading List"
date: "2026-03-24"
---

### Alternative Formats

PDF [Link](https://www.dropbox.com/scl/fi/nc1tlsaz6cyj1nilt6htr/Oral-IR-Chicago.pdf?rlkey=n1qvio9yl2amhy5vz35fhr429&e=1&dl=0)

Spreadsheet Exported from Zotero [Link](https://docs.google.com/spreadsheets/d/1mABo3aVTTulbuSrQ4nUqxk0h4-01qaXa/edit?usp=sharing&ouid=108142157213912250194&rtpof=true&sd=true)

### References

Abbott, Kenneth W., Jessica F. Green, and Robert O. Keohane. “Organizational Ecology and Institutional Change in Global Governance.” International Organization 70, no. 2 (2016): 247–77. https://doi.org/10.1017/S0020818315000338.

Abbott, Kenneth W., Robert Keohane, Andrew Moravcsik, Anne-Marie Slaughter, and Duncan Snidal. “The Concept of Legalization.” International Organization 54, no. 3 (2000): 401–19. https://doi.org/10.1162/002081800551271.

Abdelal, Rawi. “Privilege and Obligation: The OECD and Its Code of Liberalization.” In Capital Rules: The Construction of Global Finance, 86–122. Harvard University Press, 2007.

Abdelal, Rawi, Mark Blyth, and Craig Parsons. “Introduction: Constructing the International Economy.” In Constructing the International Economy, edited by Rawi Abdelal, Mark Blyth, and Craig Parsons, 1–19. Cornell University Press, 2011.

———. “Re-Constructing IPE.” In Constructing the International Economy, edited by Rawi Abdelal, Mark Blyth, and Craig Parsons, 1–19. Cornell University Press, 2011.

Acharya, Amitav. “Culture, Security, Multilateralism: The ‘ASEAN Way’ and Regional Order.” Contemporary Security Policy 19, no. 1 (1998): 55–84. https://doi.org/10.1080/13523269808404179.

———. “Do Norms and Identity Matter? Community and Power in Southeast Asia’s Regional Order.” The Pacific Review 18, no. 1 (March 2005): 95–118. https://doi.org/10.1080/09512740500047199.

Adamsky, Dmitry Dima. “Cultural Underpinnings of Current Russian Nuclear and Security Strategy.” In Crossing Nuclear Thresholds, 173–198. Springer, 2018.

Aday, Sean, Steven Livingston, and Maeve Hebert. “Embedding the Truth: A Cross-Cultural Analysis of Objectivity and Television Coverage of the Iraq War.” Harvard International Journal of Press/Politics 10, no. 1 (January 2005): 3–21. https://doi.org/10.1177/1081180X05275727.

Adcock, Robert, and David Collier. “Measurement Validity: A Shared Standard for Qualitative and Quantitative Research.” American Political Science Review 95, no. 3 (September 2001): 529–46. https://doi.org/10.1017/S0003055401003100.

Adler, Emanuel, and Michael N. Barnett. “A Framework for the Study of Security Communities.” In Security Communities, edited by Emanuel Adler and Michael N. Barnett, 29–65. Cambridge Studies in International Relations ; 62. Cambridge ;New York: Cambridge University Press, 1998. http://search.trln.org.prox.lib.ncsu.edu/search?id=UNCb3176009;

Adler-Nissen, Rebecca. “Stigma Management in International Relations: Transgressive Identities, Norms, and Order in International Society.” International Organization 68, no. 1 (January 2014): 143–76. https://doi.org/10.1017/S0020818313000337.

Adler-Nissen, Rebecca, and Vincent Pouliot. “Power in Practice: Negotiating the International Intervention in Libya.” European Journal of International Relations 20, no. 4 (December 2014): 889–911. https://doi.org/10.1177/1354066113512702.

Ahmed, Amel, and Rudra Sil. “When Multi-Method Research Subverts Methodological Pluralism—or, Why We Still Need Single-Method Research.” Perspectives on Politics 10, no. 4 (December 2012): 935–53. https://doi.org/10.1017/S1537592712002836.

Ahram, Ariel I. “Concepts and Measurement in Multimethod Research.” Political Research Quarterly 66, no. 2 (June 2013): 280–91. https://doi.org/10.1177/1065912911427453.

Alaranta, Toni. “Russia and the Idea of Eurasia in Turkey’s Strategic Culture Paradigms.” In Strategic Culture in Russia’s Neighborhood, edited by Katalin Miklossy and Hanna Smith, 1st ed., 163–84. United States: Lexington Books, 2019.

Albanese, Catherine L. America, Religions, and Religion. 5th ed. Australia ; Belmont, CA: Thomson/Wadsworth, 2013.

———. “Civil Religion: Millennial Politics and History.” In America, Religions, and Religion, 432–62. Wadsworth Pub., 1999.

Allison, Roy. “Russia and the Post-2014 International Legal Order: Revisionism and Realpolitik.” International Affairs 93, no. 3 (2017): 519–543.

Allred, Keith J. “Peacekeepers and Prostitutes: How Deployed Forces Fuel the Demand for Trafficked Women and New Hope for Stopping It.” Armed Forces & Society 33, no. 1 (October 2006): 5–23. https://doi.org/10.1177/0095327X06288803.

Almond, Gabriel A., Russell J. Dalton, Jr. G. Bingham Powell, and Kaare Strøm. European Politics Today. 4th ed. New York: Longman, 2010.

Alvarez, Jose. “International Organizations: Then and Now.” The American Journal of International Law 100, no. 2 (2006): 324–47. https://doi.org/10.1017/S0002930000016687.

Anderson, Benedict R. O’G. Imagined Communities: Reflections on the Origin and Spread of Nationalism. Rev. ed. London ; New York: Verso, 2006.

Andreas, Peter. “Illicit International Political Economy: The Clandestine Side of Globalization.” Review of International Political Economy 11, no. 3 (June 2004): 641–52. https://doi.org/10.1080/0969229042000252936.

Anton, Anatole. “Socialist Voices.” In Toward a New Socialism, edited by Anatole Anton and Richard Schmitt, 21–52. Lexington Books, 2007.

Armacost, Barbara E. “Organizational Culture and Police Misconduct.” George Washington Law Review 72 (2003): 453. https://doi.org/10.2139/ssrn.412620.

Asad, Talal. Genealogies of Religion: Discipline and Reasons of Power in Christianity and Islam. JHU Press, 2009.

Asher, Herbert. Polling and the Public : What Every Citizen Should Know. Book, Whole. Washington, D.C.: CQ Press, 2012. http://search.trln.org/search?id=DUKE004942584.

Auerswald, David P., and Stephen M. Saideman. NATO in Afghanistan: Fighting Together, Fighting Alone. Princeton: University Press, 2014.

Autesserre, Séverine. Peaceland: Conflict Resolution and the Everyday Politics of International Intervention. New York, NY, USA: Cambridge University Press, 2014.

Avant, Deborah D., Martha Finnemore, and Susan K. Sell, eds. Who Governs the Globe? Cambridge Studies in International Relations, Book, Whole. Cambridge, UK ; New York: Cambridge University Press, 2010. http://search.trln.org/search?id=DUKE004345768; Cover image (http://proxy.lib.duke.edu/login?url=http://assets.cambridge.org/97805211/98912/cover/9780521198912.jpg).

Avramenko, Richard. “Tocqueville and the Religion of Democracy.” Perspectives on Political Science 41, no. 3 (July 2012): 125–37. https://doi.org/10.1080/10457097.2012.692638.

Axelrod, Robert M. The Evolution of Cooperation. Rev. ed. New York: Basic Books, 2006.

Bache, Ian, Stephen George, and Simon Bulmer. “Economic and Monetary Union.” In Politics in the European Union, Third., 402–21. OUP Oxford, 2011.

Bair, Jennifer. “Beyond the Maquila Model? Nafta and the Mexican Apparel Industry.” Industry and Innovation 9, no. 3 (December 2002): 203–25. https://doi.org/10.1080/1366271022000034462.

Balaam, David N., and Michael Veseth. Readings in International Political Economy. Prentice Hall, 1996.

Bales, Kevin. “Human Trafficking: A Worldwide Concern.” In Understanding Global Slavery: A Reader, 126–52. University of California Press, 2005.

Balfour, Sebastian. “Spain from 1931 to the Present.” In Spain: A History, edited by Raymond Carr, 243–82. Oxford, UK: Oxford University Press, 2000. http://ukcatalogue.oup.com/.

Bancroft, Angus. “Modernity, Space and the Outsider.” In Roma and Gypsy-Travellers in Europe: Modernity, Race, Space, and Exclusion, 22–33. Ashgate, 2005.

———. “Segregation of Roma and Gypsy-Travellers.” In Roma and Gypsy-Travellers in Europe: Modernity, Race, Space, and Exclusion, 51–77. Ashgate, 2005.

———. “The Gypsies Metamorphoses: Race, Racialization and Racial Action in Europe.” In Roma and Gypsy-Travellers in Europe: Modernity, Race, Space, and Exclusion, 34–50. Ashgate, 2005.

Barbieri, Katherine, and Gerald Schneider. “Globalization and Peace: Assessing New Directions in the Study of Trade and Conflict.” Journal of Peace Research 36, no. 4 (July 1999): 387–404. https://doi.org/10.1177/0022343399036004001.

Barnes, Whitney Abernathy. “Alexis de Tocqueville: Civil Religion, Race, and the Roots of French Universalism, 1830–1857.” In The French Revolution and Religion in Global Perspective, edited by Bryan A. Banks and Erica Johnson, 97–119. Cham: Springer International Publishing, 2017. https://doi.org/10.1007/978-3-319-59683-9_5.

Barnett, Michael N., and Martha Finnemore. “The Politics, Power, and Pathologies of International Organizations.” International Organization 53, no. 4 (1999): 699–732. https://doi.org/10.1162/002081899551048.

Barton, Benjamin. “The Emergence of the EEAS a Retrospective on the Institutional Wrangling for the Soul of European Diplomacy.” In European Union Diplomacy : Coherence, Unity and Effectiveness, edited by Dieter Mahncke and Sieglinde Gstöhl, 63–88. New York: P.I.E. Peter Lang, 2012.

Baum, Matthew A., and Philip B.K. Potter. “The Relationships Between Mass Media, Public Opinion, and Foreign Policy: Toward a Theoretical Synthesis.” Annual Review of Political Science 11, no. 1 (June 2008): 39–65. https://doi.org/10.1146/annurev.polisci.11.060406.214132.

Beers, Daniel J. “A Tale of Two Transitions: Exploring the Origins of Post-Communist Judicial Culture in Romania and the Czech Republic.” Demokratizatsiya 18, no. 1 (2010): 28–55. https://doi.org/10.3200/DEMO.18.1.28-55.

Bellah, Robert N. “Civil Religion in America.” Daedalus, 1967, 1–21.

———. “Civil Religion in America.” Daedalus 134, no. 4 (September 2005): 40–55. https://doi.org/10.1162/001152605774431464.

Bellamy, Alex J. “Libya and the Responsibility to Protect: The Exception and the Norm.” Ethics & International Affairs 25, no. 03 (2011): 263–269. https://doi.org/10.1017/S0892679411000219.

Bennett, Andrew. “The Mother of All Isms: Causal Mechanisms and Structured Pluralism in International Relations Theory.” European Journal of International Relations 19, no. 3 (September 2013): 459–81. https://doi.org/10.1177/1354066113495484.

Bennett, Bruce W., and Jennifer Lind. “The Collapse of North Korea: Military Missions and Requirements.” International Security 36, no. 2 (October 2011): 84–119. https://doi.org/10.1162/ISEC_a_00057.

Bennett, Stephen Earl, and Richard S. Flickinger. “Americans’ Knowledge of U.S. Military Deaths in Iraq, April 2004 to April 2008.” Armed Forces & Society 35, no. 3 (April 2009): 587–604. https://doi.org/10.1177/0095327X08324764.

Bergan, Daniel E. “The Draft Lottery and Attitudes Towards the Vietnam War.” Public Opinion Quarterly 73, no. 2 (2009): 379–84. https://doi.org/10.1093/poq/nfp024.

Berger, Thomas U. “Dealing with Difficult Pasts: Japan’s ‘History Problem’ from a Theoretical and Comparative Perspective.” In East Asia’s Haunted Present: Historical Memories and the Resurgence of Nationalism, edited by Tsuyoshi Hasegawa and Kazuhiko Tōgō, 17–41. PSI Reports (Westport, Conn.). Westport, Conn: Praeger Security International, 2008.

Berger, Thomas U. “From Sword to Chrysanthemum: Japan’s Culture of Anti-Militarism.” International Security 17, no. 4 (1993): 119–150. https://doi.org/10.2307/2539024.

———. “Power and Purpose in Pacific East Asia: A Constructivist Interpretation.” In International Relations Theory and the Asia-Pacific, edited by G. John Ikenberry and Micahel Mastanduno, 387–419. New York: Columbia University Press, 2003.

Berinsky, Adam J. “Assuming the Costs of War: Events, Elites, and American Public Support for Military Conflict.” Journal of Politics 69, no. 4 (2007): 975–97. https://doi.org/10.1111/j.1468-2508.2007.00602.x.

Berinsky, Adam J., and James N. Druckman. “The Polls—Review.” Public Opinion Quarterly 71, no. 1 (2007): 126–41. https://doi.org/10.1093/poq/nfl049.

Berman, Sheri. “Civil Society and the Collapse of the Weimar Republic.” World Politics 49, no. 3 (April 1997): 401–29. https://doi.org/10.1353/wp.1997.0008.

Bermeo, Nancy. “Interests, Inequality, and Illusion in the Choice for Fair Elections.” Comparative Political Studies 43, no. 8–9 (August 2010): 1119–1147. https://doi.org/10.1177/0010414010370438.

“Bermeo_2010_Interests, Inequality, and Illusion in the Choice for Fair Elections.Pdf,” n.d.

Bernhard, Michael, Christopher Reenock, and Timothy Nordstrom. “The Legacy of Western Overseas Colonialism on Democratic Survival.” International Studies Quarterly 48, no. 1 (March 2004): 225–250. https://doi.org/10.1111/j.0020-8833.2004.00298.x.

Betts, Richard K. “Wealth, Power, and Instability: East Asia and the United States after the Cold War.” International Security 18, no. 3 (1993): 34. https://doi.org/10.2307/2539205.

Beyond the Secular West. Columbia University Press, 2016. https://doi.org/10.7312/bilg17080.

Bickerton, Chris J., Bastien Irondelle, and Anand Menon. “Security Co‐operation beyond the Nation‐State: The EU’s Common Security and Defence Policy.” JCMS: Journal of Common Market Studies 49, no. 1 (2011): 1–21. https://doi.org/10.1111/j.1468-5965.2010.02126.x.

Biedenkopf, Kurt H, Bronisław Geremek, Krzysztof Michalski, Reflection Group on the Spiritual and Cultural Dimension of Europe, European Commission, and Directorate K - Social sciences and humanities; foresight. The spiritual and cultural dimension of Europe: Reflection Group initiated by the President of the European Commission and coordinated by the Institue for Human Sciences : concluding remarks. Luxembourg: Office for Official Publications of the European Union, 2005.

Biehl, Heiko, Bastian Giegerich, and Alexandra Jonas. “Introduction.” In Strategic Cultures in Europe, edited by Heiko Biehl, Bastian Giegerich, and Alexandra Jonas, 7–17. Wiesbaden: Springer Fachmedien Wiesbaden, 2013. https://doi.org/10.1007/978-3-658-01168-0.

———, eds. Strategic Cultures in Europe. Wiesbaden: Springer Fachmedien Wiesbaden, 2013. https://doi.org/10.1007/978-3-658-01168-0.

Biemer, P. P. “Total Survey Error: Design, Implementation, and Evaluation.” Public Opinion Quarterly 74, no. 5 (January 1, 2010): 817–48. https://doi.org/10.1093/poq/nfq058.

Bilder, Richard B. “International Dispute Settlement and the Role of International Adjudication.” In The International Court of Justice at a Crossroads, edited by Lori Fisler Damrosch, 155–80. Transnational Publishers, Incorporated, 1987.

Bimber, Bruce, Andrew Flanagin, and Cynthia Stohl. “Involvement in Organizational Collective Action in an Era of Technological Change.” In Collective Action in Organizations: Interaction and Engagement in an Era of Technological Change, 1–36. Communication, Society and Politics. Cambridge: Cambridge University Press, 2012. https://doi.org/10.1017/CBO9780511978777.002.

———. “Participatory Styles, the Individual, and the Contemporary Organization.” In Collective Action in Organizations: Interaction and Engagement in an Era of Technological Change, 165–188. Communication, Society and Politics. Cambridge: Cambridge University Press, 2012. https://doi.org/10.1017/CBO9780511978777.007.

———. “The Collective Action Space.” In Collective Action in Organizations: Interaction and Engagement in an Era of Technological Change, 74–105. Communication, Society and Politics. Cambridge: Cambridge University Press, 2012. https://doi.org/10.1017/CBO9780511978777.004.

———. “The Contemporary Media Environment and the Evolution of Boundaries in Organization-Based Collective Action.” In Collective Action in Organizations: Interaction and Engagement in an Era of Technological Change, 37–73. Communication, Society and Politics. Cambridge: Cambridge University Press, 2012. https://doi.org/10.1017/CBO9780511978777.003.

Biscop, Sven. “European Defence: Give PESCO a Chance.” Survival 60, no. 3 (May 4, 2018): 161–80. https://doi.org/10.1080/00396338.2018.1470771.

———. European Strategy in the 21st Century: New Future for Old Power. Routledge Studies in European Security and Strategy. London ; New York, NY: Routledge, Taylor & Francis Group, 2019.

———. Oratio pro PESCO. Egmont-The Royal Institute for International Relations, 2017.

———. “The EU Global Strategy: Realpolitik with European Characteristics.” Egmont Institute, 2016, 91–100.

Bishop, George F., and Stephen T. Mockabee. “Comparability of Measurement in Public Opinion Polls.” Survey Practice 4, no. 6 (December 1, 2011): 1–5. https://doi.org/10.29115/SP-2011-0031.

Blais, André. “Introduction.: Is It Rational to Vote?” In To Vote or Not to Vote: The Merits and Limits of Rational Choice Theory, 1–16. University of Pittsburgh Press, 2000. http://www.jstor.org/stable/j.ctt5hjrrf.4.

Blaydes, Lisa, and Eric Chaney. “The Feudal Revolution and Europe’s Rise: Political Divergence of the Christian West and the Muslim World before 1500 CE.” American Political Science Review 107, no. 1 (February 2013): 16–34. https://doi.org/10.1017/S0003055412000561.

Blaydes, Lisa, and Drew A. Linzer. “The Political Economy of Women’s Support for Fundamentalist Islam.” World Politics 60, no. 4 (2008 2007): 576–609.

“Blaydes_Chaney_2013_The Feudal Revolution and Europe’s Rise.Pdf,” n.d.

Bloch-Elkon, Yaeli. “The Polls—Trends: Public Perceptions and the Threat of International Terrorism after 9/11.” Public Opinion Quarterly 75, no. 2 (2011): 366–92. https://doi.org/10.1093/poq/nfr004.

Blockmans, Steven. “The EU’s Modular Approach to Defence Integration: An Inclusive, Ambitious and Legally Binding PESCO?” Common Market Law Review 55, no. 6 (2018): 1785–1826.

Blockmans, Steven, and Marja-Liisa Laatsit. “The European External Action Service: Enhancing Coherence in EU External Action?” In EU External Relations Law and Policy in the Post-Lisbon Era, edited by Paul James Cardwell, 135–59. T. M. C. Asser Press, 2012. http://dx.doi.org/10.1007/978-90-6704-823-1_7.

Bloomfield, Alan. “Time to Move On: Reconceptualizing the Strategic Culture Debate.” Contemporary Security Policy 33, no. 3 (December 2012): 437–61. https://doi.org/10.1080/13523260.2012.727679.

Blum, Gabriella. “Bilateralism, Multilateralism, and the Architecture of International Law.” Harvard International Law Journal 49, no. 2 (2008): 323.

Boettcher, William A., and Michael D. Cobb. “‘Don’t Let Them Die in Vain’: Casualty Frames and Public Tolerance for Escalating Commitment in Iraq.” Journal of Conflict Resolution 53, no. 5 (October 2009): 677–97. https://doi.org/10.1177/0022002709339047.

———. “Echoes of Vietnam?: Casualty Framing and Public Perceptions of Success and Failure in Iraq.” Journal of Conflict Resolution 50, no. 6 (December 2006): 831–54. https://doi.org/10.1177/0022002706293665.

Bogaards, Matthijs. “The Favourable Factors for Consociational Democracy: A Review.” European Journal of Political Research 33, no. 4 (1998): 475–96. https://doi.org/10.1111/1475-6765.00392.

Boix, Carles, and Susan Carol Stokes. “Endogenous Democratization.” World Politics 55, no. 4 (December 11, 2003): 517–49. https://doi.org/10.1353/wp.2003.0019.

“Boix_Stokes_2003_Endogenous Democratization.Pdf,” n.d.

Bolton, John R. “Should We Take Global Governance Seriously Symposium: AEI Conference Trends in Global Governance: Do They Threaten American Sovereignty.” Chicago Journal of International Law 1, no. 2 (2000): 205–22.

Bossong, Raphael, and Thorsten Benner. “The Case for a Public Administration Turn in the Study of the EU’s Civilian Crisis Management.” Journal of European Public Policy 17, no. 7 (2010): 1074–86. https://doi.org/10.1080/13501763.2010.505814.

Bowen, John R. “Regulating Islam.” In Why the French Don’t Like Headscarves: Islam, the State, and Public Space, 34–62. Princeton University Press, 2010.

———. “Remembering Laïcité.” In Why the French Don’t Like Headscarves: Islam, the State, and Public Space, 11–33. Princeton University Press, 2010.

Bowman, Kirk, Fabrice Lehoucq, and James Mahoney. “Measuring Political Democracy: Case Expertise, Data Adequacy, and Central America.” Comparative Political Studies 38, no. 8 (October 2005): 939–70. https://doi.org/10.1177/0010414005277083.

Brachet, Gérard. “The Origins of the ‘Long-Term Sustainability of Outer Space Activities’ Initiative at UN COPUOS.” Space Policy 28, no. 3 (2012): 161–65. https://doi.org/10.1016/j.spacepol.2012.06.007.

Bradlow, Daniel D. “Rapidly Changing Functions and Slowly Evolving Structures: The Troubling Case of the IMF.” Proceedings of the Annual Meeting (American Society of International Law) 94, no. Journal Article (2000): 152–59. https://doi.org/10.1017/S0272503700055488.

Brady, Henry E. Causation and Explanation in Social Science. Edited by Janet M. Box-Steffensmeier, Henry E. Brady, and David Collier. Vol. 1. Oxford University Press, 2009. https://doi.org/10.1093/oxfordhb/9780199286546.003.0010.

Brady, Henry E., and David Collier, eds. Rethinking Social Inquiry: Diverse Tools, Shared Standards. 2nd ed. Lanham, Md: Rowman & Littlefield Publishers, 2010.

Brady, Henry E, David Collier, and Jason Seawright. “Refocusing the Discussion of Methodology.” In Rethinking Social Inquiry: Diverse Tools, Shared Standards, edited by Henry E. Brady and David Collier, 2nd ed., 15–31. Lanham, Md: Rowman & Littlefield Publishers, 2010.

Brander, James A. “Rationales for Strategic Trade and Industrial Policy.” In Strategic Trade Policy and the New International Economics, edited by Paul R. Krugman, 23–46. MIT Press, 1986.

Brands, Hal. American Grand Strategy in the Age of Trump. Washington, D.C: Brookings Institution Press, 2018. http://www.jstor.org/stable/10.7864/j.ctt1vjqnvw.

Breuer, Fabian. “Sociological Institutionalism, Socialisation and the Brusselisation of CSDP.” In Explaining the EU’s Common Security and Defence Policy : Theory in Action, edited by Xymena Kurowska and Fabian Breuer, 111–35. Palgrave Studies in European Union Politics; Palgrave Studies in European Union Politics. Houndmills, Basingstoke, Hampshire ;New York: Palgrave Macmillan, 2012. http://search.trln.org/search?id=UNCb7048008.

Brooks, Stephen G. “Economic Actors’ Lobbying Influence on the Prospects for War and Peace.” International Organization 67, no. 4 (October 2013): 863–88. https://doi.org/10.1017/S0020818313000283.

Brubaker, Rogers. “The Return of Assimilation? Changing Perspectives on Immigration and Its Sequels in France, Germany, and the United States.” Ethnic and Racial Studies 24, no. 4 (January 2001): 531–48. https://doi.org/10.1080/01419870120049770.

Brzezinski, Mark F., and Leszek Garlicki. “Judicial Review in Post-Communist Poland: The Emergence of a Rechtsstaat.” Stanford Journal of International Law 31, no. 1 (1995): 13–60.

Büchs, Milena. “How Legitimate Is the Open Method of Co-Ordination?*.” JCMS: Journal of Common Market Studies 46, no. 4 (September 2008): 765–86. https://doi.org/10.1111/j.1468-5965.2008.00804.x.

Bugaric, Bojan. “Courts as Policy-Makers: Lessons from Transition.” Harvard International Law Journal 42, no. 1 (2001): 247–88.

Bull, Hedley. “International Law and International Order.” In The Anarchical Society: A Study of Order in World Politics, 122–55. Book, Whole. New York: Palgrave, 2002. http://search.trln.org/search?id=DUKE003160001.

———. The Anarchical Society: A Study of Order in World Politics. Book, Whole. New York: Palgrave, 2002. http://search.trln.org/search?id=DUKE003160001.

Bunche, Valerie. “After the Elections: Explaining Divergent Regimes Trajectories.” In Defeating Authoritarian Leaders in Postcommunist Countries, 2011.

———. “Failed Cases: Azerbaijan, Armenia and Belarus.” In Defeating Authoritarian Leaders in Postcommunist Countries, 2011.

Burgoon, Brian. “Globalization and Backlash: Polayni’s Revenge?” Review of International Political Economy 16, no. 2 (June 26, 2009): 145–77. https://doi.org/10.1080/09692290802408832.

Burke, Róisín. “Shaming the State: Sexual Offences by UN Military Peacekeepers and the Rhetoric of Zero Tolerance.” In Rethinking Peacekeeping, Gender Equality and Collective Security, edited by Gina Heathcote and Dianne Otto, 70–95. Thinking Gender in Transnational Times. London: Palgrave Macmillan UK, 2014. https://doi.org/10.1057/9781137400215_4.

Buterbaugh, Kevin, and Richard M. Fulton. “Conclusions: Foundations for the New Round.” In The WTO Primer: Tracing Trade’s Visible Hand through Case Studies, 177–93. Palgrave Macmillan, 2008.

———. “The Beef Over Beef: Food Safety Standards and the WTO.” In The WTO Primer: Tracing Trade’s Visible Hand through Case Studies, 105–22. Palgrave Macmillan, 2008.

———. “The WTO: Structures, Issues, and Challenges.” In The WTO Primer: Tracing Trade’s Visible Hand through Case Studies, 67–84. Palgrave Macmillan, 2008.

Byers, Michael, and Simon Chesterman. “Changing the Rules about Rules? Unilateral Humanitarian Intervention and the Future of International Law.” In Humanitarian Intervention: Ethical, Legal and Political Dilemmas, edited by J. L. Holzgrefe and Robert O. Keohane, 177–203. Cambridge: Cambridge University Press, 2003. https://doi.org/10.1017/CBO9780511494000.006.

Byrnes, Timothy A., and Peter J. Katzenstein. Religion in an Expanding Europe. Cambridge University Press, 2006.

Calhoun, Craig J., Mark Juergensmeyer, and Jonathan VanAntwerpen, eds. Rethinking Secularism. Oxford, N.Y: Oxford University Press, 2011.

Campbell, John L. “Institutional Analysis and the Role of Ideas in Political Economy.” Theory and Society 27, no. 3 (1998): 33.

Carothers, Thomas. “The Rule of Law Revival.” Foreign Affairs 77, no. 2 (1998): 95–106. https://doi.org/10.2307/20048791.

Carson, Lisa. “Pre-Deployment ‘Gender’ Training and the Lack Thereof for Australian Peacekeepers.” Australian Journal of International Affairs 70, no. 3 (May 3, 2016): 275–92. https://doi.org/10.1080/10357718.2015.1133561.

Casanova, José. “Cosmopolitanism, the Clash of Civilizations and Multiple Modernities.” Edited by Reimon Bachika and Markus S Schulz. Current Sociology 59, no. 2 (March 2011): 252–67. https://doi.org/10.1177/0011392110391162.

———. Public Religions in the Modern World. Chicago: University of Chicago Press, 1994.

Cha, Taesuh. “The Return of Jacksonianism: The International Implications of the Trump Phenomenon.” The Washington Quarterly 39, no. 4 (October 2016): 83–97. https://doi.org/10.1080/0163660X.2016.1261562.

Chan, S. “Commerce between Rivals: Realism, Liberalism, and Credible Communication across the Taiwan Strait.” International Relations of the Asia-Pacific 9, no. 3 (September 1, 2009): 435–67. https://doi.org/10.1093/irap/lcp001.

Chappell, Laura. “Differing Member State Approaches to the Development of the EU Battlegroup Concept: Implications for CSDP.” European Security 18, no. 4 (December 1, 2009): 417–39. https://doi.org/10.1080/09662839.2010.498419.

Chappell, Laura, and Petar Petrov. “The European Defence Agency and Permanent Structured Cooperation: Are We Heading Towards Another Missed Opportunity?” Defence Studies 12, no. 1 (March 1, 2012): 44–66. https://doi.org/10.1080/14702436.2012.683973.

“Chapter 1 PDF Expert Wrong Page Numbers,” n.d.

Charney, Jonathan I. “Self-Determination: Chechnya, Kosovo, and East Timor Commentary.” Vanderbilt Journal of Transnational Law 34, no. 2 (2001): 455–68.

Charnovitz, Steve. “Nongovernmental Organizations and International Law.” American Journal of International Law 100, no. 2 (April 2006): 348–72. https://doi.org/10.1017/S0002930000016699.

Checkel, Jeffrey T., and Peter J. Katzenstein. “The Politicization of European Identities.” In European Identity, edited by Jeffrey T. Checkel and Peter J. Katzenstein, 1–28. Contemporary European Politics. Cambridge, UK ; New York: Cambridge University Press, 2009.

Cheneval, Francis, and Kalypso Nicolaidis. “The Social Construction of Demoicracy in the European Union.” European Journal of Political Theory 16, no. 2 (April 1, 2017): 235–60. https://doi.org/10.1177/1474885116654696.

Chinkin, Christine. “Rethinking Legality/Legitimacy after the Iraq War.” In Legality and Legitimacy in Global Affairs, edited by Richard A. Falk, Mark Juergensmeyer, and Vesselin Popovski, 219–47. New York: Oxford University Press, 2012. http://search.trln.org/search?id=DUKE005323147.

Cho, Y. C. “Collective Identity Formation on the Korean Peninsula: United States’ Different North Korea Policies, Kim Dae-Jung’s Sunshine Policy, and United States-South Korea-North Korea Relations.” International Relations of the Asia-Pacific 10, no. 1 (January 1, 2010): 93–128. https://doi.org/10.1093/irap/lcp016.

Christiano, Tom. “Democracy.” In The Stanford Encyclopedia of Philosophy, edited by Edward N. Zalta, Fall 2018. Metaphysics Research Lab, Stanford University, 2018. https://plato.stanford.edu/archives/fall2018/entries/democracy/.

Chugrov, Sergei V. “Russian Foreign Policy and Human Rights: Conflicted Culture and Uncertain Policy.” In Human Rights and Comparative Foreign Policy, edited by David P. Forsythe, 149–77. Tokyo ; New York: United Nations University Press, 2000.

Chwaszcza, Christine. “Game Theory.” In Approaches and Methodologies in the Social Sciences: A Pluralist Perspective, edited by Donatella Della Porta and Michael Keating, 139–61. Cambridge: Cambridge University Press, 2008. http://search.trln.org.prox.lib.ncsu.edu/search?id=DUKE004053254;

Clark, Andrew M., and Thomas B. Christie. “Ready... Ready... Drop!: A Content Analysis of Coalition Leaflets Used in the Iraq War.” Gazette (Leiden, Netherlands) 67, no. 2 (April 2005): 141–54. https://doi.org/10.1177/0016549205050128.

Clarke, Killian. “Social Forces and Regime Change: Beyond Class Analysis.” World Politics 69, no. 3 (July 2017): 569–602. https://doi.org/10.1017/S0043887117000119.

Clemens, Elisabeth S. “Organizational Repertoires and Institutional Change: Women’s Groups and the Transformation of US Politics, 1890-1920.” American Journal of Sociology 98, no. 4 (1993): 755–798. https://doi.org/10.1086/230089.

Cobb, Michael D., and Mark T. Nance. “The Consequences of Measuring Non-Attitudes about Foreign Trade Preferences.” Survey Practice 4, no. 6 (December 1, 2011): 3071. https://doi.org/10.29115/SP-2011-0030.

Cohn, Marjorie. “Nato Bombing of Kosovo: Humanitarian Intervention or Crime against Humanity?” International Journal for the Semiotics of Law 15, no. 1 (2002): 79–106. https://doi.org/10.1023/A:1015043810758.

Coleman, James S. “Social Capital in the Creation of Human Capital.” American Journal of Sociology 94 (1988): 95– 120. https://doi.org/10.1086/228943.

Colgan, Jeff D. “Where Is International Relations Going? Evidence from Graduate Training.” International Studies Quarterly 60, no. 3 (September 2016): 486–98. https://doi.org/10.1093/isq/sqv017.

Collier, David, Henry E. Brady, and Jason Seawright. “Introduction to the Second Edition: A Sea Change in Political Methodology.” In Rethinking Social Inquiry: Diverse Tools, Shared Standards, edited by Henry E. Brady and David Collier, 2nd ed., 1–10. Lanham, Md: Rowman & Littlefield Publishers, 2010.

Collier, David, Henry E Brady, and Jason Seawright. “Sources of Leverage in Causal Inference: Toward an Alternative View of Methodology.” In Rethinking Social Inquiry: Diverse Tools, Shared Standards, edited by Henry E. Brady and David Collier, 2nd ed., 161–99. Lanham, Md: Rowman & Littlefield Publishers, 2010.

Collier, David, and Steven Levitsky. “Democracy with Adjectives: Conceptual Innovation in Comparative Research.” World Politics 49, no. 3 (April 1997): 430–51. https://doi.org/10.1353/wp.1997.0009.

Collier, David, and James E. Mahon. “Conceptual ‘Stretching’ Revisited: Adapting Categories in Comparative Analysis.” American Political Science Review 87, no. 4 (December 1993): 845–55. https://doi.org/10.2307/2938818.

Collier, Ruth Berins, and David Collier. “Framework: Critical Junctures and Historical Legacies.” In Shaping the Political Arena, 27–39. Critical Junctures, the Labor Movement, and Regime Dynamics in Latin America. University of Notre Dame Press, 2002. https://doi.org/10.2307/j.ctvpj74pj.8.

“Collier_Collier_2002_Framework.Pdf,” n.d.

Collins, Jane L. “Mapping a Global Labor Market: Gender and Skill in the Globalizing Garment Industry.” Gender & Society 16, no. 6 (December 2002): 921–40. https://doi.org/10.1177/089124302237895.

Collins, Stephen D. “Europe’s United Future after Brexit: Brexit Has Not Killed the European Union, Rather It Has Eliminated the Largest Obstacle to EU Consolidation.” Global Change, Peace & Security 29, no. 3 (September 2, 2017): 311–16. https://doi.org/10.1080/14781158.2017.1385597.

Coonen, Stephen J. “The Widening Military Capabilities Gap between the United States and Europe: Does It Matter?” Parameters 36, no. 3 (2006): 67–84.

Cornish, Paul, and Geoffrey Edwards. “Beyond the EU/NATO Dichotomy: The Beginnings of a European Strategic Culture.” International Affairs 77, no. 3 (July 1, 2001): 587–603. https://doi.org/10.1111/1468-2346.00208.

Crawford, Neta C. “Human Nature and World Politics: Rethinking `Man’.” Edited by Ken Booth. International Relations 23, no. 2 (June 2009): 271–88. https://doi.org/10.1177/0047117809104639.

Cristi, Marcela. “Durkheim’s Political Sociology. Civil Religion, Nationalism and Cosmopolitanism.” In Holy Nations and Global Identities, edited by Brian Jacobsen, Margit Warburg, and Annika Hvithamar, 47–78. Brill, 2009. https://doi.org/10.1163/ej.9789004178281.i-310.41.

Dahl Thruelsen, Peter, and Danish Institute for International Studies. NATO in Afghanistan: What Lessons Are We Learning, and Are We Willing to Adjust? Copenhagen: DIIS, 2007.

Dancygier, Rafaela M. Immigration and Conflict in Europe. New York, N.Y.: Cambridge Univ. Press, 2010.

“Dancygier_2010_Immigration and Conflict in Europe.Pdf,” n.d.

Dannenbaum, Tom. “Translating the Standard of Effective Control into a System of Effective Accountability: How Liability Should Be Apportioned for Violations of Human Rights by Member State Troop Contingents Serving as United Nations Peacekeepers.” Harv. Int’l LJ 51 (2010): 113.

Darden, Keith, and Anna Maria Grzymała-Busse. “The Great Divide: Literacy, Nationalism, and the Communist Collapse.” World Politics 59, no. 1 (October 2006): 83–115. https://doi.org/10.1353/wp.2007.0015.

“Darden_Grzymała-Busse_2006_The Great Divide.Pdf,” n.d.

David, Roman, and Susanne Y. P Choi. “Victims on Transitional Justice: Lessons from the Reparation of Human Rights Abuses in the Czech Republic.” Human Rights Quarterly 27, no. 2 (2005): 392–435. https://doi.org/10.1353/hrq.2005.0016.

Davie, Grace. “Global Civil Religion: A European Perspective.” Sociology of Religion 62, no. 4 (2001): 455–473. https://doi.org/10.2307/3712436.

Davis, Martha F. “Upstairs, Downstairs: Subnational Incorporation of International Human Rights Law at the End of an Era Symposium: International Law and the Constitution: Terms of Engagement: Panel I: The Contemporary Relevance of International Human Rights for Constitutional Law and Social Justice: Case Studies and Limitations.” Fordham Law Review 77, no. 2 (2009 2008): 411–38.

De Coning, Cedric, and Karsten Friis. “Coherence and Coordination The Limits of the Comprehensive Approach.” Journal of International Peacekeeping 15, no. 1–2 (2011): 1–2. https://doi.org/10.1163/187541110X540553.

Deutsch, Karl W. “Social Mobilization and Political Development.” American Political Science Review 55, no. 3 (1961): 493–514. https://doi.org/10.2307/1952679.

Deutsch, Karl Wolfgang. Political Community and the North Atlantic Area: International Organization in the Light of Historical Experience. Princeton University Press, 1957.

“Deutsch_1961_Social Mobilization and Political Development.Pdf,” n.d.

Devroye, Jennifer. “The Case of D.H. and Others v. The Czech Republic Notes & Comments.” Northwestern University Journal of International Human Rights 7, no. 1 (2009): 81–102.

Diehl, Paul F., and Brian Frederking, eds. The Politics of Global Governance: International Organizations in an Interdependent World. 4th Revised edition edition. Boulder, Colo: Lynne Rienner Publishers Inc, 2010.

Diehl, Paul F., Jennifer Reifschneider, and Paul R. Hensel. “United Nations Intervention and Recurring Conflict.” International Organization 50, no. 4 (1996): 683–700. https://doi.org/10.1017/S0020818300033555.

DiMaggio, Paul, and Walter W. Powell. “Introduction.” In The New Institutionalism in Organizational Analysis, edited by Paul DiMaggio and Walter W. Powell, 1–38. Chicago: University of Chicago Press, 1991. http://search.trln.org/search?id=UNCb2382932.

———. “The Iron Cage Revisited: Institutional Isomorphism and Collective Rationality in Organizational Fields.” In The New Institutionalism in Organizational Analysis, edited by Paul DiMaggio and Walter W. Powell, 63–82. Chicago: University of Chicago Press, 1991. http://search.trln.org.prox.lib.ncsu.edu/search?id=UNCb2382932;

Dixon, William J., and Paul D. Senese. “Democracy, Disputes, and Negotiated Settlements.” Journal of Conflict Resolution 46, no. 4 (August 2002): 547–71. https://doi.org/10.1177/0022002702046004004.

Dodd, Stuart C. “On Reliability in Polling, A Sociometric Study of Errors of Polling in War Zones.” Sociometry 7, no. 3 (1944): 265–82. https://doi.org/10.2307/2785095.

Doner, Richard F., Bryan K. Ritchie, and Dan Slater. “Systemic Vulnerability and the Origins of Developmental States: Northeast and Southeast Asia in Comparative Perspective.” International Organization 59, no. 02 (April 2005). https://doi.org/10.1017/S0020818305050113.

Doyle, Michael W. “Three Pillars of the Liberal Peace.” American Political Science Review 99, no. 3 (August 2005): 463–66. https://doi.org/10.1017/S0003055405051798.

Doyle, Michael W., and Nicholas Sambanis. “International Peacebuilding: A Theoretical and Quantitative Analysis.” American Political Science Review 94, no. 4 (December 2000): 779–801. https://doi.org/10.2307/2586208.

———. Making War and Building Peace: United Nations Peace Operations. Princeton Paperbacks. Princeton, N.J: Princeton University Press, 2006.

Drezner, Daniel W. “Club Standards and International Finance.” In All Politics Is Global: Explaining International Regulatory Regimes, 119–48. Princeton University Press, 2008.

———. “The Global Governance of the Internet.” In All Politics Is Global : Explaining International Regulatory Regimes, 91–118. Princeton, N.J.: Princeton University Press, 2007. http://www2.lib.ncsu.edu/catalog/record/UNCb5165930; Table of contents only (http://www.loc.gov/catdir/toc/ecip0615/2006017741.html).

Duke, Simon. “The Pre- and Post-Brexit Evolution of the EU’s Common Security and Defence Policy.” In Will Brexit Damage Our Security and Defence?, by Simon Duke, 27–38. Cham: Springer International Publishing, 2019. https://doi.org/10.1007/978-3-319-96107-1_2.

Dunne, Timothy. “The English School.” In International Relations Theories: Discipline and Diversity, edited by Timothy Dunne, Milja Kurki, and Steve Smith, Third edition., 132–52. Oxford: Oxford University Press, 2013.

Dunne, Timothy, Milja Kurki, and Steve Smith, eds. International Relations Theories: Discipline and Diversity. Third edition. Oxford: Oxford University Press, 2013.

Durkheim, Émile. The Elementary Forms of the Religious Life. Translated by Joseph Ward Swain, 2012. http://www.gutenberg.org/ebooks/41360.

Easterly, William Russell. “You Can’t Plan a Market.” In The White Man’s Burden: Why the West’s Efforts to Aid the Rest Have Done So Much Ill and So Little Good, 60–111. Penguin, 2006.

Eichenberg, Richard C. “Victory Has Many Friends: U.S. Public Opinion and the Use of Military Force, 1981–2005.” International Security 30, no. 1 (July 1, 2005): 140–77. https://doi.org/10.1162/0162288054894616.

Einstein, Albert. “Why Socialism?” Monthly Review: An Independent Socialist Magazine 56, no. 1 (May 2004): 44–50. https://doi.org/10.14452/MR-056-01-2004-05_5.

Eitelhuber, Norbert. “The Russian Bear: Russian Strategic Culture and What It Implies for the West.” Connections 9, no. 1 (2009): 1–28.

Elman, Colin. “Explanatory Typologies in Qualitative Studies of International Politics.” International Organization 59, no. 02 (April 2005). https://doi.org/10.1017/S0020818305050101.

Eltahawy, Mona. “Why Do They Hate Us?” Foreign Policy (blog), April 23, 2012. https://foreignpolicy.com/2012/04/23/why-do-they-hate-us/.

Encarnación, Omar G. “Labor and Pacted Democracy: Post-Franco Spain in Comparative Perspective.” Comparative Politics 33, no. 3 (2001): 337–355. https://doi.org/10.2307/422407.

Encarnación, Omar G.Winter. “Spain After Franco: Lessons in Democratization.” World Policy Journal. Pp 18, no. 4 (2001): 35–44. https://doi.org/10.1215/07402775-2002-1005.

Eng, Kok-Thay. Redefining Genocide, n.d.

Engberg, Katarina. The EU and Military Operations: A Comparative Analysis. London, UNITED KINGDOM: Routledge, 2013. http://ebookcentral.proquest.com/lib/uci/detail.action?docID=1524162.

Engle, Karen. “The Grip of Sexual Violence: Reading UN Security Council Resolutions on Human Security.” In Rethinking Peacekeeping, Gender Equality and Collective Security, edited by Gina Heathcote and Dianne Otto, 23–47. Thinking Gender in Transnational Times. London: Palgrave Macmillan UK, 2014. https://doi.org/10.1057/9781137400215_2.

“Epilogue: Reactionary and Revolutionary Imagery,” n.d.

Eriksen, Erik Oddvar, and Jarle Weigård. Understanding Habermas : Communicative Action and Deliberative Democracy. Book, Whole. London ; New York: Continuum, 2003. http://search.trln.org/search?id=NCSU1638973.

Ermarth, Fritz W. “Russian Strategic Culture in Flux: Back to the Future?” In Strategic Culture and Weapons of Mass Destruction, 85–96. Springer, 2009.

Esping-Andersen, Gosta. The Three Worlds of Welfare Capitalism. Princeton University Press, 1990.

Esty, D. C., and A. L. I. Moffa. “Why Climate Change Collective Action Has Failed and What Needs to Be Done Within and Without the Trade Regime.” Journal of International Economic Law 15, no. 3 (September 1, 2012): 777–91. https://doi.org/10.1093/jiel/jgs033.

“Extracted Annotation Kindle,” n.d.

“Extracted Annotations (1/27/2020, 10:52:20 PM),” n.d.

“Extracted Annotations (1/27/2020, 10:55:59 PM)"Popular Agitation First Alerts Concerned Officials to Poor Policy Impleme,” n.d.

“Extracted Annotations (1/27/2020, 11:01:31 PM)"Consider, for Example, Chile,Which in 1985 Had a per Capita Gross Domesti,” n.d.

“Extracted Annotations (1/27/2020, 11:03:38 PM),” n.d.

“Extracted Annotations (1/27/2020, 11:04:32 PM),” n.d.

“Extracted Annotations (1/27/2020, 11:10:09 PM),” n.d.

“Extracted Annotations (1/27/2020, 11:11:17 PM)"Why Do Actors in Transitional Governments Choose to Hold Fair Elections w,” n.d.

“Extracted Annotations (1/27/2020, 11:14:10 PM),” n.d.

“Extracted Annotations (1/27/2020, 11:14:55 PM),” n.d.

“Extracted Annotations (1/27/2020, 11:16:14 PM)"The First Is to Identify Historical Patterns of Class Formation and State,” n.d.

“Extracted Annotations (1/27/2020, 11:21:44 PM),” n.d.

“Extracted Annotations (1/27/2020, 11:24:27 PM)"In Some of These Countries the Fi Rst Free Elections Returned the Communi,” n.d.

“Extracted Annotations (1/27/2020, 11:27:11 PM),” n.d.

“Extracted Annotations (1/27/2020, 11:33:24 PM),” n.d.

“Extracted Annotations (1/28/2020, 7:36:01 PM),” n.d.

“Extracted Annotations (1/28/2020, 8:06:12 PM),” n.d.

“Extracted Annotations (1/28/2020, 8:17:07 PM),” n.d.

“Extracted Annotations (1/28/2020, 8:19:52 PM),” n.d.

“Extracted Annotations (1/28/2020, 9:19:40 PM)"focus Primarily on Legacies Operating at the Individual Level, Which Can b,” n.d.

“Extracted Annotations Kindle,” n.d.

“Extracted Annotations Kindle,” n.d.

“Extracted Annotations Kindle,” n.d.

“Extracted Annotations Kindle,” n.d.

Fasulo, Linda M. An Insider’s Guide to the UN. New Haven, Conn: Yale University Press, 2004.

Fearon, James D. “Rationalist Explanations for War.” International Organization 49, no. 3 (1995): 379–414. https://doi.org/10.1017/S0020818300033324.

Fearon, James D., and David D. Laitin. “Explaining Interethnic Cooperation.” American Political Science Review 90, no. 4 (December 1996): 715–35. https://doi.org/10.2307/2945838.

“Fearon_Laitin_1996_Explaining Interethnic Cooperation.Pdf,” n.d.

Feaver, Peter D., Gunther Hellmann, Randall L. Schweller, Jeffrey W. Taliaferro, William C. Wohlforth, Jeffrey W. Legro, and Andrew Moravcsik. “Brother, Can You Spare a Paradigm? (Or Was Anybody Ever a Realist?).” International Security 25, no. 1 (July 2000): 165–93. https://doi.org/10.1162/016228800560426.

Feiock, Richard C. “Metropolitan Governance and Institutional Collective Action.” Urban Affairs Review 44, no. 3 (January 2009): 356–77. https://doi.org/10.1177/1078087408324000.

Feldman, Stanley, and John Zaller. “The Political Culture of Ambivalence: Ideological Responses to the Welfare State.” American Journal of Political Science 36, no. 1 (1992): 268–307. https://doi.org/10.2307/2111433.

Fellmeth, Aaron Xavier. “State Regulation of Sexuality in International Human Rights Law and Theory.” William and Mary Law Review 50, no. 3 (2008): 797–936.

Fierke, Karin M. “Constructivism.” In International Relations Theories, edited by Tim Dunne, Milja Kurki, and Steve Smith, Third edition., 187–204. Oxford: Oxford University Press, 2013.

Finn, John E. “The Rule of Law and Judicial Independence in Newly Democratic Regimes.” Good Society Journal 13, no. 3 (2004): 12–16. https://doi.org/10.1353/gso.2005.0018.

Fiott, Daniel. The CARD on the EU Defence Table. Paris: ISS, 2017. https://www.iss.europa.eu/sites/default/files/EUISSFiles/Alert_10_CARD_0.pdf.

Fiott, Daniel, Antonio Missiroli, and Thierry Tardy. Permanent Structured Cooperation: What’s in a Name? Chaillot Papers, No 142 (November 2017). Luxembourg: EU Institute for Security Studies, 2017. https://www.iss.europa.eu/content/permanent-structured-cooperation-what%E2%80%99s-name.

“First Published in 1979,” n.d.

Flynn, Brendan. “PESCO and the Challenges of Multilateral Defence Cooperation for Ireland: More of the Same or Sea Change?” Irish Studies in International Affairs 29 (2018): 73. https://doi.org/10.3318/isia.2018.29.07.

Fordham, Benjamin O., and Katja B. Kleinberg. “How Can Economic Interests Influence Support for Free Trade?” International Organization 66, no. 2 (April 2012): 311–28. https://doi.org/10.1017/S0020818312000057.

Fortna, Virginia Page. “Does Peacekeeping Keep Peace? International Intervention and the Duration of Peace After Civil War.” International Studies Quarterly 48, no. 2 (June 2004): 269–92. https://doi.org/10.1111/j.0020-8833.2004.00301.x.

———. “Inside and out: Peacekeeping and the Duration of Peace after Civil and Interstate Wars.” International Studies Review 5, no. 4 (2003): 97–114. https://doi.org/10.1111/j.1079-1760.2003.00504010.x.

Fortna, Virginia Page, and Lise Morjé Howard. “Pitfalls and Prospects in the Peacekeeping Literature.” Annual Review of Political Science 11, no. 1 (June 2008): 283–301. https://doi.org/10.1146/annurev.polisci.9.041205.103022.

Foster, Sheila R. “Collective Action and the Urban Commons.” Notre Dame L.Rev. 87, no. Journal Article (2011): 57–133.

Foucault, Michel. “Questions of Method.” In The Foucault Effect: Studies in Governmentality: With Two Lectures by and an Interview with Michel Foucault, edited by Michel Foucault, Graham Burchell, Colin Gordon, and Peter Miller, 73–86. Chicago: University of Chicago Press, 1991.

———. “The Body of the Condemned.” In Discipline and Punish: The Birth of the Prison, 3–31. Vintage Books, 1995.

Frear, Matthew. “Evolution and Adaptation in Belarusian Strategic Culture.” In Strategic Culture in Russia’s Neighborhood, edited by Katalin Miklossy and Hanna Smith, 1st ed., 229–57. United States: Lexington Books, 2019.

Friedberg, Aaron L. “Ripe for Rivalry: Prospects for Peace in a Multipolar Asia.” International Security 18, no. 3 (1993): 5. https://doi.org/10.2307/2539204.

———. “The Future of U.S.-China Relations: Is Conflict Inevitable?” International Security 30, no. 2 (October 2005): 7–45. https://doi.org/10.1162/016228805775124589.

Friedman, Milton, and Rose Friedman. “The Power of the Market.” In Free to Choose: A Personal Statement, 9–37. Houghton Mifflin Harcourt, 1990.

———. “The Tyranny of Controls.” In Free to Choose: A Personal Statement, 9–37. Houghton Mifflin Harcourt, 1990.

Fukuyama, Francis. The End of History and the Last Man. New York : Toronto : New York: Free Press ; Maxwell Macmillan Canada ; Maxwell Macmillan International, 1992.

Fuller, Lon L. “Positivism and Fidelity to Law: A Reply to Professor Hart.” Harvard Law Review 71, no. 4 (February 1958): 630. https://doi.org/10.2307/1338226.

Furia, Peter A., and Russell E. Lucas. “Determinants of Arab Public Opinion on Foreign Relations.” International Studies Quarterly 50, no. 3 (September 2006): 585–605. https://doi.org/10.1111/j.1468-2478.2006.00415.x.

Gadarian, Shana Kushner. “The Politics of Threat: How Terrorism News Shapes Foreign Policy Attitudes.” The Journal of Politics 72, no. 2 (April 2010): 469–83. https://doi.org/10.1017/S0022381609990910.

Gagliardone, Iginio, and Nicole A. Stremlau. “Public Opinion Research in a Conflict Zone: Grassroots Diplomacy in Darfur.” International Journal of Communication 2, no. 0 (September 25, 2008): 29.

Gaines, Brian J., James H. Kuklinski, and Paul J. Quirk. “The Logic of the Survey Experiment Reexamined.” Political Analysis 15, no. 1 (2007): 1–20. https://doi.org/10.1093/pan/mpl008.

Garlicki, Lech. “Constitutional Courts versus Supreme Courts.” International Journal of Constitutional Law 5, no. 1 (January 1, 2007): 44–68. https://doi.org/10.1093/icon/mol044.

Gartner, Scott Sigmund. “The Multiple Effects of Casualties on Public Support for War: An Experimental Approach.” American Political Science Review 102, no. 1 (February 2008): 95–106. https://doi.org/10.1017/S0003055408080027.

Gartner, Scott Sigmund, and Gary M. Segura. “War, Casualties, and Public Opinion.” Journal of Conflict Resolution 42, no. 3 (June 1998): 278–300. https://doi.org/10.1177/0022002798042003004.

Geddes, Barbara. “How the Cases You Choose Affect the Answers You Get: Selection Bias in Comparative Politics.” Political Analysis 2 (1990): 131–50. https://doi.org/10.1093/pan/2.1.131.

Geertz, Clifford. “Deep Play: Notes on the Balinese Cockfight.” In The Interpretation Of Cultures, 412–53. Basic Books, 1973.

———. “Thick Description: Toward an Interpretive Theory of Culture.” In The Interpretation Of Cultures, 3–30. Basic Books, 1973.

Gelpi, Christopher, Peter D. Feaver, and Jason Reifler. “Success Matters: Casualty Sensitivity and the War in Iraq.” International Security 30, no. 3 (January 1, 2006): 7–46. https://doi.org/10.1162/isec.2005.30.3.7.

George, Alexander L., and Andrew Bennett. “Chapter 1 Case Studies and Theory Development.” In Case Studies and Theory Development in the Social Sciences, 3–36. MIT Press, 2005. https://books.google.com/books?id=k0LEQgAACAAJ.

———. “Comparative Methods: Controlled Comparison and Within-Case Analysis.” In Case Studies and Theory Development in the Social Sciences, 151–79. MIT Press, 2005. https://books.google.com/books?id=k0LEQgAACAAJ.

———. “Process-Tracing and Historical Explanation.” In Case Studies and Theory Development in the Social Sciences, 205–32. MIT Press, 2005. https://books.google.com/books?id=k0LEQgAACAAJ.

———. “The Congruence Method.” In Case Studies and Theory Development in the Social Sciences, 181–204. MIT Press, 2005. https://books.google.com/books?id=k0LEQgAACAAJ.

Gerring, John. “Causal Mechanisms: Yes, But….” Comparative Political Studies 43, no. 11 (November 2010): 1499–1526. https://doi.org/10.1177/0010414010376911.

———. “What Makes a Concept Good? A Criterial Framework for Understanding Concept Formation in the Social Sciences.” Polity 31, no. 3 (March 1999): 357–93. https://doi.org/10.2307/3235246.

Gerring, John, and Rose McDermott. “An Experimental Template for Case Study Research.” American Journal of Political Science 51, no. 3 (July 2007): 688–701. https://doi.org/10.1111/j.1540-5907.2007.00275.x.

Geys, B. “Wars, Presidents, and Popularity: The Political Cost(s) of War Re-Examined.” Public Opinion Quarterly 74, no. 2 (June 1, 2010): 357–74. https://doi.org/10.1093/poq/nfq001.

Ghias, Shoaib A. “International Judicial Lawmaking: A Theoretical and Political Analysis of the WTO Appellate Body.” Berkeley Journal of International Law 24, no. 2 (2006): 534–53.

Gibney, Mark, Sabine C. Carey, and Steven C. Poe. “State Responsibilities.” In The Politics of Human Rights: The Quest for Dignity, 40–69. Cambridge: Cambridge University Press, 2010. https://doi.org/10.1017/CBO9780511780486.003.

Gilens, Martin, and Benjamin I. Page. “Testing Theories of American Politics: Elites, Interest Groups, and Average Citizens.” Perspectives on Politics 12, no. 3 (2014): 564–581. https://doi.org/10.1017/S1537592714001595.

Glaser, Charles L. “A U.S.-China Grand Bargain? The Hard Choice between Military Competition and Accommodation.” International Security 39, no. 4 (April 2015): 49–90. https://doi.org/10.1162/ISEC_a_00199.

Glenn, John. Neorealism versus Strategic Culture. Edited by John Glenn, Darryl Howlett, and Stuart Poore. 1st ed. Routledge, 2018. https://doi.org/10.4324/9781351152808.

———. “Realism versus Strategic Culture: Competition and Collaboration?” International Studies Review 11, no. 3 (September 1, 2009): 523–51. https://doi.org/10.1111/j.1468-2486.2009.00872.x.

———. “Russia.” In Neorealism versus Strategic Culture, edited by John Glenn, Darryl Howlett, and Stuart Poore, 1st ed., 173–203. Routledge, 2018. https://doi.org/10.4324/9781351152808.

Goertz, Gary, and James Mahoney. “Causes-of-Effects versus Effects-of-Causes.” In A Tale of Two Cultures, 41–50. Qualitative and Quantitative Research in the Social Sciences. Princeton University Press, 2012. www.jstor.org/stable/j.cttq94gh.6.

———. “Hume’s Two Definitions of Cause.” In A Tale of Two Cultures, 75–84. Qualitative and Quantitative Research in the Social Sciences. Princeton University Press, 2012. www.jstor.org/stable/j.cttq94gh.9.

Goldsmith, B. E. “Different in Asia? Developmental States, Trade, and International Conflict Onset and Escalation.” International Relations of the Asia-Pacific 13, no. 2 (May 1, 2013): 175–205. https://doi.org/10.1093/irap/lct003.

———. “Domestic Political Institutions and the Initiation of International Conflict in East Asia: Some Evidence for an Asian Democratic Peace.” International Relations of the Asia-Pacific 14, no. 1 (January 1, 2014): 59–90. https://doi.org/10.1093/irap/lct019.

Goldstein, Joshua S. Winning the War on War: The Decline of Armed Conflict Worldwide. Penguin, 2012.

Goldstein, Judith, Miles Kahler, Robert O. Keohane, and Anne-Marie Slaughter, eds. Legalization and World Politics. Book, Whole. Cambridge, Mass.: MIT Press, 2001. http://search.trln.org/search?id=UNCb3951822.

Goldstein, Judith O., Miles Kahler, Robert Keohane, and Anne-Marie Slaughter. “Introduction: Legalization and World Politics.” International Organization 54, no. 3 (2000): 385–99. https://doi.org/10.1162/002081800551262.

Goodman, Sara Wallace. “Conceptualizing and Measuring Citizenship and Integration Policy: Past Lessons and New Approaches.” Comparative Political Studies 48, no. 14 (December 2015): 1905–41. https://doi.org/10.1177/0010414015592648.

“Google Books Link.” Accessed March 12, 2018. https://books.google.com/books?id=Z4bXAwAAQBAJ.

Gorski, Philip. American Covenant: A History of Civil Religion from the Puritans to the Present. Princeton University Press, 2017. https://doi.org/10.2307/j.ctvc772b9.

Gourevitch, Peter. “The Second Image Reversed: The International Sources of Domestic Politics.” International Organization 32, no. 4 (1978): 881–911. https://doi.org/10.1017/S002081830003201X.

Gowa, Joanne. “Review: Anarchy, Egoism, and Third Images: The Evolution of Cooperation and International Relations Reviewed Work(s): The Evolution of Cooperation. by Robert Axelrod.” International Organization 40, no. 1 (1986): 167–86.

GRANT, RUTH W., and ROBERT O. KEOHANE. “Accountability and Abuses of Power in World Politics.” American Political Science Review 99, no. 1 (2005): 29. https://doi.org/10.1017/S0003055405051476.

Gray, Colin S. “Out of the Wilderness: Prime Time for Strategic Culture.” In Strategic Culture and Weapons of Mass Destruction: Culturally Based Insights into Comparative National Security Policymaking, edited by Jeannie L. Johnson, Kerry M. Kartchner, and Jeffrey Arthur Larsen, 221–41. Initiatives in Strategic Studies: Issues and Policies. New York: Palgrave Macmillan, 2009.

———. “Strategic Culture as Context: The First Generation of Theory Strikes Back.” Review of International Studies 25, no. 1 (1999): 49–69. https://doi.org/10.1017/S0260210599000492.

Greig, J. Michael. “Stepping Into the Fray: When Do Mediators Mediate?” American Journal of Political Science 49, no. 2 (April 2005): 249–66. https://doi.org/10.1111/j.0092-5853.2005.00121.x.

Greig, J. Michael, and Paul F. Diehl. “The Peacekeeping-Peacemaking Dilemma.” International Studies Quarterly 49, no. 4 (2005): 621–45.

Griesgraber, Jo Marie. “Reforms for Major New Roles of the International Monetary Fund? The IMF Post-G-20 Summit.” Global Governance 15, no. 2 (2009): 179–85. https://doi.org/10.1163/19426720-01502003.

Griffin, Penny. “Refashioning IPE: What and How Gender Analysis Teaches International (Global) Political Economy.” Review of International Political Economy 14, no. 4 (August 14, 2007): 719–36. https://doi.org/10.1080/09692290701475437.

Gronke, Paul, Darius Rejali, Dustin Drenguis, James Hicks, Peter Miller, and Bryan Nakayama. “U.S. Public Opinion on Torture, 2001–2009.” PS: Political Science & Politics 43, no. 03 (July 2010): 437–44. https://doi.org/10.1017/S1049096510000697.

Gualtieri, A. N. G. “The Environmental Accountability of the World Bank to Non-State Actors: Insights from the Inspection Panel.” British Yearbook of International Law 72 (2002): 213–254.

Gutmann, Amy, and Dennis F. Thompson. Why Deliberative Democracy? Book, Whole. Princeton: Princeton University Press, 2004. http://search.trln.org/search?id=UNCb4489259.

Haas, Ernst B. When Knowledge Is Power Three Models of Change in International Organizations. Studies in International Political Economy. Berkeley: University of California Press, 1990. http://ark.cdlib.org/ark:/13030/ft6489p0mp/.

Hall, Peter A. “ALIGNING ONTOLOGY AND METHODOLOGY IN COMPARATIVE POLITICS.” In Comparative Historical Analysis in the Social Sciences, edited by Dietrich Rueschemeyer and James Mahoney, 373–404. Cambridge Studies in Comparative Politics. Cambridge: Cambridge University Press, 2003. https://doi.org/10.1017/CBO9780511803963.012.

Hall, Peter A., and David W. Soskice. “Introduction.” In Varieties of Capitalism: The Institutional Foundations of Comparative Advantage, edited by Peter A. Hall and David W. Soskice, 1–68. Oxford [England] ; New York: Oxford University Press, 2001.

Hall, Peter A., and Rosemary Taylor C. R. “Political Science and the Three New Institutionalisms.” In Institutionalism, edited by B. Guy Peters and Jon Pierre, 1:167–93. Los Angeles, Calif. ;London: SAGE, 2007. http://search.trln.org.prox.lib.ncsu.edu/search?id=UNCb5257501;Table of contents only (http://www.loc.gov/catdir/enhancements/fy0801/2006932951-t.html);

Hallams, Ellen, and Benjamin Schreer. “Towards a Post-American Alliance? NATO Burden-Sharing after Libya.” International Affairs 88, no. 2 (2012): 313–27. https://doi.org/10.1111/j.1468-2346.2012.01073.x.

Halpin, Stanley A. “Looking over a Crowd and Picking Your Friends: Civil Rights and the Debate over the Influence of Foreign and International Human Rights Law on the Interpretation of the U.S. Constitution.” Hastings International and Comparative Law Review 30, no. 1 (2006): 1–42.

Hammond, Phillip E. “The Conditions for Civil Religion: A Comparison of the United States and Mexico.” In Varieties of Civil Religion, edited by Robert N. Bellah and Phillip E. Hammond, 40–85. Wipf and Stock Publishers, 2013.

———. “The Rudimentary Forms of Civil Religion.” In Varieties of Civil Religion, edited by Robert N. Bellah and Phillip E. Hammond, 121–37. Wipf and Stock Publishers, 2013.

Hancock, M. Donald, Christopher J. Carman, Marjorie Castle, David P. Conradt, Raffaella Y. Nanetti, Robert Leonardi, William Safran, and Stephen White. “How Is Power Used?” In Politics in Europe, 666–96. CQ Press, 2014.

———. “The Context of European Union Politics.” In Politics in Europe, 623–38. CQ Press, 2014.

———. “Where Is the Power?” In Politics in Europe, 639–56. CQ Press, 2014.

———. “Who Has the Power?” In Politics in Europe, 657–65. CQ Press, 2014.

Hardin, Russell. One for All: The Logic of Group Conflict. Princeton, N.J.: Princeton University Press, 1995. http://site.ebrary.com/id/10392645.

Harlen, Christine Margerum. “A Reappraisal of Classical Economic Nationalism and Economic Liberalism.” International Studies Quarterly 43, no. 4 (1999): 733–44.

Hart, H. L. A. “Positivism and the Separation of Law and Morals.” Harvard Law Review 71, no. 4 (February 1958): 593–629. https://doi.org/10.2307/1338225.

Hartzell, Caroline, and Matthew Hoddie. “Institutionalizing Peace: Power Sharing and Post‐Civil War Conflict Management.” American Journal of Political Science 47, no. 2 (April 2003): 318–32. https://doi.org/10.1111/1540-5907.00022.

Hassner, Ron E. “‘To Halve and to Hold’: Conflicts over Sacred Space and the Problem of Indivisibility.” Security Studies 12, no. 4 (January 2003): 1–33. https://doi.org/10.1080/09636410390447617.

Hawkesworth, M. E. “Engendering Globalization.” In Globalization and Feminist Activism, 1–28. Rowman & Littlefield, 2006.

Hebert, Laura. “Analyzing UN & NATO Responses to Sexual Misconduct in Peacekeeping Operations.” In Making Gender, Making War: Violence, Military and Peacekeeping Practices, edited by Annica Kronsell and Erika Svedberg, 121–36. Routledge, 2011.

Hedetoft, Ulf. “Nationalism as Civil Religion and Rituals of Belonging Before and After the Global Turn.” In Holy Nations and Global Identities, edited by Brian Jacobsen, Margit Warburg, and Annika Hvithamar, 253–69. Brill, 2009. https://doi.org/10.1163/ej.9789004178281.i-310.41.

Hehir, Aidan. The Responsibility to Protect : Rhetoric, Reality and the Future of Humanitarian Intervention. Book, Whole. Houndmills, Basingstoke, Hampshire ;New York: Palgrave Macmillan, 2012. http://search.trln.org/search?id=UNCb7129144.

Heinze, Eric A. “Humanitarian Intervention, the Responsibility to Protect, and Confused Legitimacy.” Human Rights & Human Welfare 11, no. Journal Article (2011): 17.

Held, David. Democracy and the Global Order : From the Modern State to Cosmopolitan Governance. Book, Whole. Stanford, CA: Stanford University Press, 1995. http://search.trln.org/search?id=DUKE002109616.

Helleiner, Eric. “Economic Nationalism as a Challenge to Economic Liberalism? Lessons from the 19th Century.” International Studies Quarterly 46, no. 3 (2002): 307–29.

Hemmer, Christopher, and Peter J. Katzenstein. “Why Is There No NATO in Asia? Collective Identity, Regionalism, and the Origins of Multilateralism.” International Organization 56, no. 3 (2002): 575–607. https://doi.org/10.1162/002081802760199890.

Herrmann, Richard K., and Jong Kun Choi. “From Prediction to Learning: Opening Experts’ Minds to Unfolding History.” International Security 31, no. 4 (2007): 132–61.

Hertel-Fernandez, Alexander. “Who Passes Business’s ‘Model Bills’? Policy Capacity and Corporate Influence in US State Politics.” Perspectives on Politics 12, no. 3 (2014): 582–602. https://doi.org/10.1017/S1537592714001601.

“Highlight (Pink) - Chapter II. Evolution and Revolution in France > Page 40 · Location 976,” n.d.

“Highlight (Pink) - Page 77 · Location 2766,” n.d.

“Highlight (Yellow) - Chapter 2. Cities, People, and Language > Page 53 · Location 1071,” n.d.

“Highlight (Yellow) - Chapter III. The American Civil War: The Last Capitalist Revolution > Page 111 · Location 2277,” n.d.

“Highlight (Yellow) - Chapter IX. The Peasants and Revolution > Page 453 · Location 8336,” n.d.

“Highlight (Yellow) - Chapter VIII. Revolution from Above and Fascism > Page 433 · Location 7991,” n.d.

“Highlight (Yellow) - Page 27 · Location 954,” n.d.

“Highlight (Yellow) - Page 48 · Location 1800,” n.d.

Hillock, Rebecca L. “Establishing the Rights of Women Globally: Has the United Nations Convention on the Elimination of All Forms of Discrimination against Women Made a Difference Comment.” Tulsa Journal of Comparative & International Law 12, no. 2 (2004): 481–514.

Hirst, Paul Q., Grahame Thompson, and Simon Bromley. “Globalization and the History of the International Economy.” In Globalization in Question, 3rd ed., 24–67. Cambridge, UK ; Malden, MA: Polity, 2009. http://catalog.hathitrust.org/api/volumes/oclc/260207408.html.

Hoekman, B., A. Mattoo, and A. Sapir. “The Political Economy of Services Trade Liberalization: A Case for International Regulatory Cooperation?” Oxford Review of Economic Policy 23, no. 3 (September 1, 2007): 367–91. https://doi.org/10.1093/oxrep/grm024.

Hofmann, Stephanie C. European Security in NATO’s Shadow: Party Ideologies and Institution Building. Cambridge, [England] ; New York: Cambridge University Press, 2013.

Holzgrefe, J. L. “The Humanitarian Intervention Debate.” In Humanitarian Intervention: Ethical, Legal and Political Dilemmas, edited by J. L. Holzgrefe and Robert O. Keohane, 15–52. Cambridge: Cambridge University Press, 2003. https://doi.org/10.1017/CBO9780511494000.002.

Hooghe, Liesbet, and Gary Marks. “Does Identity or Economic Rationality Drive Public Opinion on European Integration?” PS: Political Science & Politics 37, no. 03 (2004): 415. https://doi.org/10.1017.S1049096504004585.

Hopf, Ted. “Common-Sense Constructivism and Hegemony in World Politics.” International Organization 67, no. 2 (April 2013): 317–354. https://doi.org/10.1017/S0020818313000040.

———. “Russia Becoming Russia: A Semi-Periphery in Splendid Isolation.” In Uses of “the West,” edited by Gunther Hellmann and Benjamin Herborth, 203–28. Cambridge: Cambridge University Press, 2017. https://doi.org/10.1017/9781316717448.010.

Howard, Lise Morjé. UN Peacekeeping in Civil Wars. Cambridge ; New York: Cambridge University Press, 2008.

Howard, Marc Morje. “Postcommunist Civil Society in Comparative Perspective.” Demokratizatsiya 10, no. 3 (2002): 285.

———. “The Weakness of Postcommunist Civil Society.” Journal of Democracy 13, no. 1 (2002): 157–69. https://doi.org/10.1353/jod.2002.0008.

Howard, Peter. “Why Not Invade North Korea? Threats, Language Games, and U.S. Foreign Policy.” International Studies Quarterly 48, no. 4 (December 2004): 805–28. https://doi.org/10.1111/j.0020-8833.2004.00326.x.

Hui, Victoria Tin-bor. “Toward a Dynamic Theory of International Politics: Insights from Comparing Ancient China and Early Modern Europe.” International Organization 58, no. 01 (February 2004). https://doi.org/10.1017/S0020818304581067.

Hultman, Lisa, Jacob Kathman, and Megan Shannon. “Beyond Keeping Peace: United Nations Effectiveness in the Midst of Fighting.” American Political Science Review 108, no. 04 (2014): 737–753. https://doi.org/10.1017/S0003055414000446.

Huntington, Samuel P. The Clash of Civilizations and the Remaking of World Order. New York: Simon & Schuster, 1996.

Hurd, Elizabeth S. “A Suspension of (Dis)Belief: The Secular-Religious Binary and the Study of International Relations.” In Rethinking Secularism, edited by Craig Calhoun, Mark Juergensmeyer, and Jonathan VanAntwerpen. Oxford: Oxford University Press, 2011.

Hurrell, Andrew. “Legitimacy and the Use of Force: Can the Circle Be Squared?” In Force and Legitimacy in World Politics, edited by J. D. (James David) Armstrong, Theo Farrell, and Bice Maiguashca, 15–32. Cambridge, UK: Cambridge University Press, 2005. http://search.trln.org/search?id=DUKE004660898; Publisher description (http://proxy.lib.duke.edu/login?url=http://catdir.loc.gov/catdir/enhancements/fy0710/2007272858-d.html); Table of contents only (http://proxy.lib.duke.edu/login?url=http://catdir.loc.gov/catdir/enhancements/fy0710/2007272858-t.html); Contributor biographical information (http://proxy.lib.duke.edu/login?url=http://catdir.loc.gov/catdir/enhancements/fy0732/2007272858-b.html).

Hvithamar, Annika. “Nationalism And Civil Religion. What Is The Difference?” In Holy Nations and Global Identities, edited by Brian Jacobsen, Margit Warburg, and Annika Hvithamar, 99–118. Brill, 2009. https://doi.org/10.1163/ej.9789004178281.i-310.41.

Hvithamar, Annika, Margit Warburg, and Brian Arly Jacobsen, eds. Holy Nations and Global Identities: Civil Religion, Nationalism, and Globalisation. International Studies in Religion and Society, v. 10. Leiden ; Boston: Brill, 2009.

Hyde, Susan D. “The Observer Effect in International Politics: Evidence from a Natural Experiment.” World Politics 60, no. 1 (2007): 37–63.

Igumnova, Lyudmila. “Russia’s Strategic Culture Between American and European Worldviews.” The Journal of Slavic Military Studies 24, no. 2 (April 1, 2011): 253–73. https://doi.org/10.1080/13518046.2011.572729.

Irondelle, Bastien, Frédéric Mérand, and Martial Foucault. “Public Support for European Defence: Does Strategic Culture Matter?: Public Support for European Defence.” European Journal of Political Research 54, no. 2 (May 2015): 363–83. https://doi.org/10.1111/1475-6765.12090.

Jachtenfuchs, Markus. “The Governance Approach to European Integration.” JCMS: Journal of Common Market Studies 39, no. 2 (June 2001): 245–64. https://doi.org/10.1111/1468-5965.00287.

Jackman, Robert W., and Ross A. Miller. “Social Captial and Politics.” Annual Review of Political Science 1, no. 1 (1998): 47–73. https://doi.org/10.1146/annurev.polisci.1.1.47.

Jackson, Van. “Power, Trust, and Network Complexity: Three Logics of Hedging in Asian Security.” International Relations of the Asia-Pacific 14, no. Journal Article (2014): 331–56. https://doi.org/10.1093/irap/lcu005.

Jacoby, Wade, and Christopher Jones. “The EU Battle Groups in Sweden and the Czech Republic: What National Defense Reforms Tell Us about European Rapid Reaction Capabilities.” European Security 17, no. 2–3 (June 1, 2008): 315–38. https://doi.org/10.1080/09662830802642587.

Jakobi, Anja P. “The OECD and Crime: The Fight against Corruption and Money Laundering.” In Mechanisms of OECD Governance:International Incentives for National Policy-Making?: International Incentives for National Policy-Making?, edited by Kerstin Martens and Anja P. Jakobi, 139–60. OUP Oxford, 2010.

Janos, Andrew C. “The Politics of Backwardness in Continental Europe, 1780-1945.” World Politics 41, no. 3 (April 1989): 325–58. https://doi.org/10.2307/2010503.

“Janos_1989_The Politics of Backwardness in Continental Europe, 1780-1945.Pdf,” n.d.

Jasentuliyana, N. “Ensuring Equal Access to the Benefits of Space Technologies for All Countries.” Space Policy 10, no. 1 (1994): 7–18. https://doi.org/10.1016/0265-9646(94)90036-1.

Jentleson, Bruce W., and Rebecca L. Britton. “Still Pretty Prudent.” The Journal of Conflict Resolution 42, no. 4 (1998): 395–417. https://doi.org/10.1177/0022002798042004001.

Jetschke, Anja. “Institutionalizing ASEAN: Celebrating Europe through Network Governance.” Cambridge Review of International Affairs 22, no. 3 (2009): 407–26. https://doi.org/10.1080/09557570903107688.

Johnson, Juliet, Daniel Mügge, Leonard Seabrooke, Cornelia Woll, Ilene Grabel, and Kevin P. Gallagher. “The Future of International Political Economy: Introduction to the 20th Anniversary Issue of RIPE.” Review of International Political Economy 20, no. 5 (October 2013): 1009–23. https://doi.org/10.1080/09692290.2013.835275.

Johnson, Nicholas L. “Cleaning Up Space.” Harvard International Review 33, no. 4 (2012): 67–71.

Johnston, Alastair I. Cultural Realism: Strategic Culture and Grand Strategy in Chinese History. Princeton Studies in International History and Politics. Princeton, N.J: Princeton University Press, 1995.

Johnston, Alastair Iain. “Thinking about Strategic Culture.” International Security 19, no. 4 (1995): 32–64. https://doi.org/10.2307/2539119.

———. “Treating International Institutions as Social Environments.” International Studies Quarterly 45, no. 4 (2001): 487–515. https://doi.org/10.1111/0020-8833.00212.

Joyner, Christopher C. International Law in the 21st Century: Rules for Global Governance. New Millennium Books in International Studies. Lanham, Md: Rowman & Littlefield, 2005.

Judis, John B. “Confessions of a True Believer.” Foreign Policy, no. 172 (2009): 142–43.

Judt, Tony. “The Shape of Things to Come.” In Ill Fares the Land, 189–225. New York: Penguin Press, 2010. http://www2.lib.ncsu.edu/catalog/record/UNCb6249392.

Jupille, J., and J. A. Caporaso. “Institutionalism and the European Union: Beyond International Relations and Comparative Politics.” Annual Review of Political Science 2, no. 1 (1999): 429–44. https://doi.org/10.1146/annurev.polisci.2.1.429.

Kahler, Miles. “Defining Accountability up: The Global Economic Multilaterals.” Government and Opposition 39, no. 2 (2004): 132–58. https://doi.org/10.1111/j.1477-7053.2004.00003.x.

———. “Legalization as Strategy: The Asia-Pacific Case.” International Organization 54, no. 3 (2000): 549–71. https://doi.org/10.1162/002081800551325.

Kaiser, Wolfram. Christian Democracy and the Origins of European Union. New Studies in European History. Cambridge ; New York: Cambridge University Press, 2007.

Kaminski, Marek. Games Prisoners Play: The Tragicomic Worlds of Polish Prison. Princeton, NJ: Princeton University Press, 2004.

Kanet, Roger E. “Russian Strategic Culture, Domestic Politics and Cold War 2.0.” European Politics and Society 20, no. 2 (March 15, 2019): 190–206. https://doi.org/10.1080/23745118.2018.1545184.

Kapiszewski, Diana, Lauren M. MacLean, and Benjamin Lelan Read. Field Research in Political Science: Practices and Principles. Strategies for Social Inquiry. Cambridge, United Kingdom: Cambridge University Press, 2015.

Karim, Sabrina, and Kyle Beardsley. “Explaining Sexual Exploitation and Abuse in Peacekeeping Missions: The Role of Female Peacekeepers and Gender Equality in Contributing Countries.” Journal of Peace Research 53, no. 1 (January 1, 2016): 100–115. https://doi.org/10.1177/0022343315615506.

Karolewski, Ireneusz Pawel. “The European Union’s Civil Religion in the Making?” In Religion and Politics: European and Global Perspectives, edited by Jóhann Páll Árnason and Ireneusz Pawel Karolewski, 97–114. Edinburgh University Press, 2014.

Kastoryano, Riva. “The Politicization of Identities in France” in Negotiating Identities: States and Immigrants in France and Germany. Translated by Barbara Harshav. Princeton: Princeton University Press, 2002.

Katzenstein, Peter J. The Culture of National Security : Norms and Identity in World Politics. New York: Columbia University Press, 1996. http://www2.lib.ncsu.edu/catalog/record/DUKE002179297; Get an online version (Duke only) (http://proxy.lib.duke.edu/login?url=http://www.ciaonet.org/); Get an online version (NCSU only) (http://proxying.lib.ncsu.edu/index.php?url=http://www.ciaonet.org/book/katzenstein).

Katzenstein, Peter J., Robert O. Keohane, and Stephen D. Krasner. “International Organization and the Study of World Politics.” International Organization 52, no. 4 (1998): 645–685. https://doi.org/10.1017/S002081830003558X.

Katzenstein, Peter J., and Rudra Sil. “Rethinking Asian Security : A Case for Analytical Eclecticism.” In Rethinking Security in East Asia : Identity, Power, and Efficiency, edited by J. J. Suh, Peter J. Katzenstein, and Allen Carlson, 1–33. Stanford, CA: Stanford University Press, 2004.

Kawasaki, Tsuyoshi. “Postclassical Realism and Japanese Security Policy.” The Pacific Review 14, no. 2 (January 2001): 221–40. https://doi.org/10.1080/09512740110037361.

Keohane, Robert O. After Hegemony: Cooperation and Discord in the World Political Economy. Princeton, N.J: Princeton University Press, 1984.

———. “Governance in a Partially Globalized World ‘Presidential Address’, ‘American Political Science Association, 2000.’” The American Political Science Review 95, no. 1 (2001): 1–13.

Keohane, Robert O., Andrew Moravcsik, and Anne-Marie Slaughter. “Legalized Dispute Resolution: Interstate and Transnational.” International Organization 54, no. 3, Legalization and World Politics (2000): 457–88. https://doi.org/10.1162/002081800551299.

Kessler, Sanford. “Tocqueville on Civil Religion and Liberal Democracy.” The Journal of Politics 39, no. 1 (1977): 119–46. https://doi.org/10.2307/2129689.

Khalil, Elias L. “Organizations versus Institutions.” In Institutionalism, edited by B. Guy Peters and Jon Pierre, 4:108–28. Sage Library of Political Science; Sage Library of Political Science. Los Angeles, Calif. ;London: SAGE, 2007. http://search.trln.org.prox.lib.ncsu.edu/search?id=UNCb5257501;Table of contents only (http://www.loc.gov/catdir/enhancements/fy0801/2006932951-t.html);;

Khoo, Nicholas. “Is Realism Dead? Academic Myths and Asia’s International Politics.” Orbis 58, no. 2 (2014): 182–97. https://doi.org/10.1016/j.orbis.2014.02.007.

Kier, Elizabeth. “Culture and Military Doctrine: France between the Wars.” International Security 19, no. 4 (1995): 65. https://doi.org/10.2307/2539120.

Kim, Ji Young. “Rethinking the Role of Identity Factors: The History Problem and the Japan–South Korea Security Relationship in the Post-Cold War Period.” International Relations of the Asia-Pacific 15, no. 3 (September 2015): 477–503. https://doi.org/10.1093/irap/lcv007.

Kim, Young Sok. “Responsibility to Protect, Humanitarian Intervention and North Korea.” Journal of International Business and Law 5 (2006): 74–94.

Kindleberger, Charles P. “Dominance and Leadership in the International Economy: Exploitation, Public Goods, and Free Rides.” International Studies Quarterly 25, no. 2 (June 1981): 242. https://doi.org/10.2307/2600355.

King, Gary, Robert O. Keohane, and Sidney Verba. “Causality and Causal Inference.” In Designing Social Inquiry, STU-Student edition., 75–114. Scientific Inference in Qualitative Research. Princeton University Press, 1994. www.jstor.org/stable/j.ctt7sfxj.6.

———. “The Science in Social Science.” In Designing Social Inquiry, STU-Student edition., 3–33. Scientific Inference in Qualitative Research. Princeton University Press, 1994. www.jstor.org/stable/j.ctt7sfxj.4.

King, Lawrence P. “Central European Capitalism in Comparative Perspective.” In Beyond Varieties of Capitalism: Conflict, Contradiction, and Complementarities in the European Economy, edited by Bob Hancké, Martin Rhodes, and Mark Thatcher, 307–27. Oxford ; New York: Oxford University Press, 2007.

Kirchick, James. The End of Europe: Dictators, Demagogues, and the Coming Dark Age. New Haven: Yale University Press, 2017.

Kirshner, Jonathan. “Rationalist Explanations for War?” Security Studies 10, no. 1 (September 2000): 143–50. https://doi.org/10.1080/09636410008429423.

———. “The Tragedy of Offensive Realism: Classical Realism and the Rise of China.” European Journal of International Relations 18, no. 1 (March 2012): 53–75. https://doi.org/10.1177/1354066110373949.

Klarevas, Louis. “The ‘Essential Domino’ of Military Operations: American Public Opinion and the Use of Force.” International Studies Perspectives 3, no. 4 (November 2002): 417–37. https://doi.org/10.1111/1528-3577.t01-1-00107.

Klein, Yitzhak. “A Theory of Strategic Culture.” Comparative Strategy 10, no. 1 (January 1991): 3–23. https://doi.org/10.1080/01495939108402827.

Kontorovich, Eugene. “A Guantanamo on the Sea: The Difficulty of Prosecuting Pirates and Terrorists Essay.” California Law Review 98, no. 1 (2010): 243–76.

Kopstein, Jeffrey. “1989 as a Lens for the Communist Past and Post-Communist Future.” Contemporary European History 18, no. 3 (August 2009): 289. https://doi.org/10.1017/S0960777309005050.

Kopstein, Jeffrey S., and Jason Wittenberg. “Beyond Dictatorship and Democracy: Rethinking National Minority Inclusion and Regime Type in Interwar Eastern Europe.” Comparative Political Studies 43, no. 8–9 (August 2010): 1089–1118. https://doi.org/10.1177/0010414010370437.

———. “Deadly Communities: Local Political Milieus and the Persecution of Jews in Occupied Poland.” Comparative Political Studies 44, no. 3 (March 2011): 259–83. https://doi.org/10.1177/0010414010384370.

“Kopstein_Wittenberg_2010_Beyond Dictatorship and Democracy.Pdf,” n.d.

Kraska, James. “Freakonomics of Maritime Piracy.” The Brown Journal of World Affairs 16, no. 2 (2010): 109–19.

Krasner, Stephen D. “State Power and the Structure of International Trade.” World Politics 28, no. 3 (April 1976): 317–47. https://doi.org/10.2307/2009974.

Krueger, A. B., and J. Maleckova. “Attitudes and Action: Public Opinion and the Occurrence of International Terrorism.” Science 325, no. 5947 (September 18, 2009): 1534–36. https://doi.org/10.1126/science.1170867.

Kühn, Zdeněk. “Worlds Apart: Western and Central European Judicial Culture at the Onset of the European Enlargement.” The American Journal of Comparative Law 52, no. 3 (2004): 531–67. https://doi.org/10.2307/4144478.

Kull, Steven, Clay Ramsay, and Evan Lewis. “Misperceptions, the Media, and the Iraq War.” Political Science Quarterly 118, no. 4 (December 2003): 569–98. https://doi.org/10.1002/j.1538-165X.2003.tb00406.x.

Kuran, Timur. Private Truths, Public Lies: The Social Consequences of Preference Falsification. 1st Harvard University Press pbk. ed. Cambridge, Mass: Harvard University Press, 1997.

Kurki, Milja, and Colin Wight. “International Relations and Social Science.” In International Relations Theories: Discipline and Diversity, edited by Timothy Dunne, Milja Kurki, and Steve Smith, Third edition., 14–35. Oxford: Oxford University Press, 2013.

LaFeber, Walter. The American Age: United States Foreign Policy at Home and Abroad 1750 to the Present. 2nd edition. New York: W. W. Norton & Company, 1994.

Laity, Mark. “NATO and Libya: The Dawn of European Security Management, a Warning, or Business as Usual?” In Strategy in NATO: Preparing for an Imperfect World, edited by Liselotte Odgaard, 91–107. Palgrave Studies in Governance, Security and Development. New York: Palgrave Macmillan US, 2014. https://doi.org/10.1057/9781137382054_7.

Lála, Petr. “The Role of the United Nations in Promoting International Cooperation in Peaceful Uses of Outer Space.” Acta Astronautica 39, no. 9 (1996): 647–55. https://doi.org/10.1016/S0094-5765(97)00046-5.

Lange, Matthew K. “British Colonial Legacies and Political Development.” World Development 32, no. 6 (June 2004): 905–22. https://doi.org/10.1016/j.worlddev.2003.12.001.

Lankina, Tomila, and Lullit Getachew. “Mission or Empire, Word or Sword? The Human Capital Legacy in Postcolonial Democratic Development: MISSION OR EMPIRE.” American Journal of Political Science 56, no. 2 (April 2012): 465–83. https://doi.org/10.1111/j.1540-5907.2011.00550.x.

Lantis, Jeffrey S. “Strategic Culture and National Security Policy.” International Studies Review 4, no. 3 (2002): 87–113. https://doi.org/10.1111/1521-9488.t01-1-00266.

———. “Strategic Culture: From Clausewitz to Constructivism.” In Strategic Culture and Weapons of Mass Destruction: Culturally Based Insights into Comparative National Security Policymaking, edited by Jeannie L. Johnson, Kerry M. Kartchner, and Jeffrey A. Larsen, 33–52. Initiatives in Strategic Studies: Issues and Policies. New York: Palgrave Macmillan US, 2009. https://doi.org/10.1057/9780230618305_3.

———. “Strategic Cultures and Security Policies in the Asia-Pacific.” Contemporary Security Policy 35, no. 2 (May 4, 2014): 166–86. https://doi.org/10.1080/13523260.2014.927676.

Laudrup, Carin. “A European Battlefield: Does the EU Have a Soul? Is Religion In or Out of Place in the European Union?” Religion, State and Society 37, no. 1–2 (March 1, 2009): 51–63. https://doi.org/10.1080/09637490802693528.

Laver, Michael, and Kenneth A. Shepsle. “Government Accountability in Parliamentary Democracy.” In Democracy, Accountability, and Representation, edited by Adam Przeworski, Susan C. Stokes, and Bernard Manin, 279–96. Cambridge University Press, 1999.

Lavrakas, Paul J. “Suggestions for Improving Public Policy Polling: A Reply to Moore’s ‘Contemporary Issues with Public Policy Polls.’” Survey Practice 4, no. 6 (December 12, 2011): 3759.

Lebeck, Carl. “Accountability in Supra- and International Organizations - between Judicialization and Political Constitutionalism?” Connecticut Journal of International Law 21, no. 1 (2005): 93–126.

Lebow, Richard Ned. “Classical Realism.” In International Relations Theories: Discipline and Diversity, edited by Timothy Dunne, Milja Kurki, and Steve Smith, Third edition., 59–76. Oxford: Oxford University Press, 2013.

———. “Review: What’s So Different about a Counterfactual?” World Politics 52, no. 4 (2000): 550–85.

Leeds, Brett Ashley, and David R. Davis. “Domestic Political Vulnerability and International Disputes.” Journal of Conflict Resolution 41, no. 6 (December 1997): 814–34. https://doi.org/10.1177/0022002797041006005.

Legro, Jeffrey W., and Andrew Moravcsik. “Is Anybody Still a Realist?” International Security 24, no. 2 (1999): 5–55. https://doi.org/10.1162/016228899560130.

Leith, Katherine H., Astrid Knott, Alexander G. Mayer, and Jörg Westermann. “Germany.” In Comparative Health Systems, edited by James A. Johnson and Carleen H. Stoskopf, 146–66. Jones & Bartlett Publishers, 2010.

Leonard, Eric K., and Steven C. Roach. “From Realism to Legalization- A Rationalist Assessment of the International Criminal Court in the Democratic Republic of Congo.” In Governance, Order, and the International Criminal Court : Between Realpolitik and a Cosmopolitan Court, edited by Steven C. Roach. Oxford ; New York: Oxford University Press, 2009. http://search.trln.org/search?id=NCSU2241428; Get an online version (NCSU only) (http://proxying.lib.ncsu.edu/index.php?url=http://www.netLibrary.com/urlapi.asp?action=summary&v=1&bookid=287478).

Levi-Faur, David. “Economic Nationalism: From Friedrich List to Robert Reich.” Review of International Studies 23, no. 3 (July 1997): 359–70. https://doi.org/10.1017/S0260210597003598.

Levy, Jack, and Gary Goertz. Explaining War and Peace: Case Studies and Necessary Condition Counterfactuals. Routledge, 2007.

Levy Paluck, Elizabeth. “The Promising Integration of Qualitative Methods and Field Experiments.” The ANNALS of the American Academy of Political and Social Science 628, no. 1 (March 2010): 59–71. https://doi.org/10.1177/0002716209351510.

Lewis, Jeffrey. “The Janus Face of Brussels: Socialization and Everyday Decision Making in the European Union.” International Organization 59, no. 04 (October 2005). https://doi.org/10.1017/S0020818305050320.

Li, Xiaorong. “Asian Values and the Universality of Human Rights.” In Philosophical Dimensions of Public Policy, edited by Verna V Gehring and William A Galston, 397–408. New Brunswick, N.J.; London: Transaction, 2003.

Li, Xiaoting. “Applying Offensive Realism to the Rise of China: Structural Incentives and Chinese Diplomacy toward the Neighboring States.” International Relations of the Asia-Pacific 16, no. 2 (May 2016): 241–71. https://doi.org/10.1093/irap/lcv019.

Lichbach, Mark I. “What Makes Rational Peasants Revolutionary? Dilemma, Paradox, and Irony in Peasant Collective Action.” World Politics 46, no. 03 (1994): 383–418. https://doi.org/10.2307/2950687.

Lieberman, Evan S. “Nested Analysis as a Mixed-Method Strategy for Comparative Research.” American Political Science Review 99, no. 3 (August 2005): 435–52. https://doi.org/10.1017/S0003055405051762.

Liff, Adam P., and G. John Ikenberry. “Racing toward Tragedy?: China’s Rise, Military Competition in the Asia Pacific, and the Security Dilemma.” International Security 39, no. 2 (October 2014): 52–91. https://doi.org/10.1162/ISEC_a_00176.

Lijphart, Arend. “Consociational Democracy.” World Politics 21, no. 2 (1969): 207–25. https://doi.org/10.2307/2009820.

Lind, J.M. “Pacifism or Passing the Buck?: Testing Theories of Japanese Security.” Policy. International Security 29, no. 1 (2004): 92–121. https://doi.org/10.1162/0162288041762968.

Lindstrom, Gustav. Enter the EU Battlegroups. Chaillot Paper 97. Paris: EU Institute for Security Studies, 2007.

Linz, Juan J., and Alfred Stepan. “Political Identities and Electoral Sequences: Spain, the Soviet Union, and Yugoslavia.” Daedalus 121, no. 2 (1992): 123–39.

Lipman, Maria. “Putin’s ‘Besieged Fortress’ and Its Ideological Arms.” In The State of Russia: What Comes Next?, edited by Maria Lipman and Nikolay Petrov, 110–36. London: Palgrave Macmillan UK, 2015. https://doi.org/10.1057/9781137548115_7.

Lipschutz, Ronnie D. “From Local Knowledge and Practice to Global Environmental Governance.” In Approaches to Global Governance Theory, edited by Martin Hewson and Timothy J. Sinclair, 259–83. SUNY Series in Global Politics; SUNY Series in Global Politics. Albany, NY: State University of New York Press, 1999. http://www2.lib.ncsu.edu/catalog/record/DUKE002628320.

Lipset, Seymour Martin. “Some Social Requisites of Democracy: Economic Development and Political Legitimacy.” The American Political Science Review 53, no. 1 (1959): 69–105. https://doi.org/10.2307/1951731.

“Lipset_1959_Some Social Requisites of Democracy.Pdf,” n.d.

Locke, Richard M., and Kathleen Thelen. “Apples and Oranges Revisited: Contextualized Comparisons and the Study of Comparative Labor Politics.” Politics & Society 23, no. 3 (September 1995): 337–67. https://doi.org/10.1177/0032329295023003004.

Lopez, Anthony C., Rose McDermott, and Michael Bang Petersen. “States in Mind: Evolution, Coalitional Psychology, and International Politics.” International Security 36, no. 2 (October 2011): 48–83. https://doi.org/10.1162/ISEC_a_00056.

Luebbert, Gregory M. “Social Foundations of Political Order in Interwar Europe.” World Politics 39, no. 4 (July 1987): 449–78. https://doi.org/10.2307/2010288.

“Luebbert_1987_Social Foundations of Political Order in Interwar Europe.Pdf,” n.d.

Lupu, Noam, and Leonid Peisakhin. “The Legacy of Political Violence across Generations.” American Journal of Political Science 61, no. 4 (October 2017): 836–51. https://doi.org/10.1111/ajps.12327.

Lynch, Cecelia. “A Neo-Weberian Approach to Religion in International Politics.” International Theory 1, no. 3 (November 2009): 381–408. https://doi.org/10.1017/S1752971909000116.

———. “A Neo-Weberian Approach to Studying Religion and Violence.” Millennium: Journal of International Studies 43, no. 1 (September 2014): 273–90. https://doi.org/10.1177/0305829814541506.

Lynch, Cecelia, and Tanya B. Schwarz. “Humanitarianism’s Proselytism Problem.” International Studies Quarterly 60, no. 4 (December 2016): 636–46. https://doi.org/10.1093/isq/sqw024.

Lyytikäinen, Minna, Nicola Popovic, César Nicolás Penson, and A. Santo Domingo. Gender Training for Peacekeepers: Preliminary Overview of United Nations Peace Support Operations. United Nations International Research and Training Institute for the Advancement of Women (UN-INSTRAW), 2007. http://www.peacewomen.org/assets/file/Resources/UN/un-instraw_gendertrainingpk_2007.pdf.

Macdonald, Kate. “Globalising Justice within Coffee Supply Chains? Fair Trade, Starbucks and the Transformation of Supply Chain Governance.” Third World Quarterly 28, no. 4 (June 2007): 793–812. https://doi.org/10.1080/01436590701336663.

“Machine Generated Contents Note: Part I. The Puzzles and Arguments: 1. To Extract and to Organize; 2. States and the Reg,” n.d.

MacQueen, Norrie. Humanitarian Intervention and the United Nations. Book, Whole. Edinburgh: Edinburgh University Press, 2011. http://search.trln.org/search?id=DUKE004959571.

Mahmood, S. “Secularism, Hermeneutics, and Empire: The Politics of Islamic Reformation.” Public Culture 18, no. 2 (April 1, 2006): 323–47. https://doi.org/10.1215/08992363-2006-006.

Mahoney, James. “After KKV: The New Methodology of Qualitative Research.” World Politics 62, no. 1 (January 2010): 120–47. https://doi.org/10.1017/S0043887109990220.

———. “STRATEGIES OF CAUSAL ASSESSMENT IN COMPARATIVE HISTORICAL ANALYSIS.” In Comparative Historical Analysis in the Social Sciences, edited by Dietrich Rueschemeyer and James Mahoney, 337–72. Cambridge Studies in Comparative Politics. Cambridge: Cambridge University Press, 2003. https://doi.org/10.1017/CBO9780511803963.011.

Mahoney, James, and Dietrich Rueschemeyer. “COMPARATIVE HISTORICAL ANALYSIS Achievements and Agendas.” In Comparative Historical Analysis in the Social Sciences, edited by Dietrich Rueschemeyer and James Mahoney, 3–38. Cambridge Studies in Comparative Politics. Cambridge: Cambridge University Press, 2003. https://doi.org/10.1017/CBO9780511803963.002.

Maliniak, Daniel, Ryan Powers, and Barbara F. Walter. “The Gender Citation Gap in International Relations.” International Organization 67, no. 4 (October 2013): 889–922. https://doi.org/10.1017/S0020818313000209.

Malone, David. “Introduction.” In The UN Security Council: From the Cold War to the 21st Century, edited by David Malone, 1–16. Lynne Rienner Publishers, 2004.

Mansfield, Edward D., and Diana C. Mutz. “Support for Free Trade: Self-Interest, Sociotropic Politics, and Out-Group Anxiety.” International Organization 63, no. 3 (July 2009): 425–57. https://doi.org/10.1017/S0020818309090158.

March, James G., and Johan P. Olsen. “The New Institutionalism: Organizational Factors in Political Life.” In Institutionalism, edited by B. Guy Peters and Jon Pierre, 1:83–109. Sage Library of Political Science; Sage Library of Political Science. Los Angeles, Calif. ;London: SAGE, 2007. http://search.trln.org/search?id=UNCb5257501; Table of contents only (http://www.loc.gov/catdir/enhancements/fy0801/2006932951-t.html).

Marshall, Katherine. “Nuts and Bolts: How the World Bank Functions.” In The World Bank: From Reconstruction to Development to Equity, 59–92. Routledge, 2008.

Marten, Kimberly. “The ‘KGB State’ and Russian Political and Foreign Policy Culture.” The Journal of Slavic Military Studies 30, no. 2 (April 3, 2017): 131–51. https://doi.org/10.1080/13518046.2017.1270053.

Marx, Karl. “Wage-Labour and Capital.” In Karl Marx: Selected Writings, edited by David McLellan, 275–94. Oxford University Press, 2000.

Marxism, Albert EinsteinTopics:, and Socialism Places: Global. “Monthly Review | Why Socialism?” Monthly Review (blog), May 1, 2009. https://monthlyreview.org/2009/05/01/why-socialism/.

Mastro, Oriana Skylar. “The Problems of the Liberal Peace in Asia.” Survival 56, no. 2 (March 4, 2014): 129–58. https://doi.org/10.1080/00396338.2014.901742.

MATCZAK, MARCIN, MATYAS BENCZE, and ZDENEK KÜHN. “Constitutions, EU Law and Judicial Strategies in the Czech Republic, Hungary and Poland.” Journal of Public Policy 30, no. 1 (2010): 81–99. https://doi.org/10.1017/S0143814X09990195.

Mathews, Jessica T. “Power Shift.” Foreign Affairs 76, no. 1 (1997): 50–66. https://doi.org/10.2307/20047909.

Mavelli, Luca, and Erin K. Wilson. “Postsecularism and International Relations.” In Routledge Handbook of Religion and Politics, by Jeffrey Haynes, 250–69. edited by Jeffrey Haynes, 2nd ed. Routledge, 2016. https://doi.org/10.4324/9781315643922-16.

Mayroz, Eyal. “Ever Again? The United States, Genocide Suppression, and the Crisis in Darfur.” Journal of Genocide Research 10, no. 3 (September 2008): 359–88. https://doi.org/10.1080/14623520802305735.

McDermott, Rose. “The Ten Commandments of Experiments.” PS: Political Science & Politics 46, no. 03 (July 2013): 605–10. https://doi.org/10.1017/S1049096513000577.

McGarry, John, and Brendan O’Leary. “Introduction: Consociational Theory and Northern Ireland.” In The Northern Ireland Conflict: Consociational Engagements, edited by John McGarry and Brendan O’Leary, 1–61. OUP Oxford, 2004.

McNamara, Kathleen R. “Of Intellectual Monocultures and the Study of IPE.” Review of International Political Economy 16, no. 1 (February 16, 2009): 72–84. https://doi.org/10.1080/09692290802524117.

Mearsheimer, J. J. “The Gathering Storm: China’s Challenge to US Power in Asia.” The Chinese Journal of International Politics 3, no. 4 (December 1, 2010): 381–96. https://doi.org/10.1093/cjip/poq016.

Mearsheimer, John J. “Structural Realism.” In International Relations Theories, edited by Tim Dunne, Milja Kurki, and Steve Smith, Third edition., 77–93. Oxford: Oxford University Press, 2013.

———. “The False Promise of International Institutions.” International Security 19, no. 3 (1994): 5–49. https://doi.org/10.2307/2539078.

———. The Tragedy of Great Power Politics. New York: Norton, 2001.

Mercer, Jonathan. “Anarchy and Identity.” International Organization 49, no. 2 (1995): 229–52. https://doi.org/10.1017/S0020818300028381.

Merrills, J. G. International Dispute Settlement. Book, Whole. Cambridge, UK ; New York: Cambridge University Press, 2011. http://search.trln.org/search?id=DUKE005088052; Cover image (http://proxy.lib.duke.edu/login?url=http://assets.cambridge.org/97805211/99094/cover/9780521199094.jpg).

Meyer, Christoph O. “Convergence Towards a European Strategic Culture? A Constructivist Framework for Explaining Changing Norms.” European Journal of International Relations 11, no. 4 (December 1, 2005): 523–49. https://doi.org/10.1177/1354066105057899.

Meyer, Howard N. “Not a Whole World’s Court.” In The World Court in Action: Judging Among the Nations, 37–49. Maryland: Rowman & Littlefield Publishers, 2002.

———. “The Part-World Court Functions.” In The World Court in Action: Judging Among the Nations, 51–59. Rowman & Littlefield, 2002.

Meyer, John W., and Brian Rowan. “Institutionalized Organizations: Formal Structure as Myth and Ceremony.” In The New Institutionalism in Organizational Analysis, edited by Paul DiMaggio and Walter W. Powell, 41–62. Chicago: University of Chicago Press, 1991. http://search.trln.org.prox.lib.ncsu.edu/search?id=UNCb2382932;

Miklóssy, Katalin, and Silviu Miloiu. “Interactive Strategic Cultures: Romania and Moldova.” In Strategic Culture in Russia’s Neighborhood, edited by Katalin Miklossy and Hanna Smith, 1st ed., 117–140. United States: Lexington Books, 2019.

Miklóssy, Katalin, and Justyna Pierzynska. “Regional Strategic Culture in the Visegrad Countries: Poland and Hungary.” In Strategic Culture in Russia’s Neighborhood, edited by Katalin Miklossy and Hanna Smith, 1st ed., 83–114. United States: Lexington Books, 2019.

Miklóssy, Katalin, and Hanna Smith. “Concluding Remarks: In-Between-Ness and Strategic Culture.” In Strategic Culture in Russia’s Neighborhood:, edited by Katalin Miklossy and Hanna Smith, 1st ed., 259–266. United States: Lexington Books, 2019.

———. “Introduction: Reviewing Strategic Culture in the Russian Neighborhood.” In Strategic Culture in Russia’s Neighborhood, edited by Katalin Miklossy and Hanna Smith, 1st ed., ix–xxiii. United States: Lexington Books, 2019.

Miller, Raymond C. “The Classical Marxist Model and World View.” In International Political Economy: Contrasting World Views, 171–92. Routledge, 2008.

———. “The Market Model and World View.” In International Political Economy: Contrasting World Views, 15–38. Routledge, 2008.

Milner, Helen V. “The Political Economy of International Trade.” Annual Review of Political Science 2, no. 1 (1999): 91–114. https://doi.org/10.1146/annurev.polisci.2.1.91.

Milner, Helen V., and Keiko Kubota. “Why the Move to Free Trade? Democracy and Trade Policy in the Developing Countries.” International Organization 59, no. 01 (January 2005). https://doi.org/10.1017/S002081830505006X.

Minkenberg, Michael. “Christian Identity? European Churches and the Issue of Turkey’s EU Membership.” Comparative European Politics 10, no. 2 (April 2012): 149–79. https://doi.org/10.1057/cep.2011.24.

Miyashita, Akitoshi. “Where Do Norms Come from? Foundations of Japan’s Postwar Pacifism1.” International Relations of the Asia-Pacific 7, no. 1 (January 1, 2007): 99–120. https://doi.org/10.1093/irap/lci135.

Mondré, Aletta, Gerald Neubauer, Achim Helmedach, and Bernhard Zangl. “Uneven Judicialization: Comparing International Dispute Settlement in Security, Trade, and the Environment.” New Global Studies 4, no. 1 (2010): 1–32. https://doi.org/10.2202/1940-0004.1081.

Moore, Barrington. Social Origins of Dictatorship and Democracy: Lord and Peasant in the Making of the Modern World. Boston: Beacon Press, 1993.

Moore, David W. “Three Schools of Thought on ‘Public Opinion’ Measures.” Survey Practice 4, no. 6 (December 1, 2011): 1–5. https://doi.org/10.29115/SP-2011-0027.

“Moore_1993_Social Origins of Dictatorship and Democracy.Pdf,” n.d.

Moravcsik, Andrew. “Taking Preferences Seriously: A Liberal Theory of International Politics.” International Organization 51, no. 4 (1997): 513–553. https://doi.org/10.1162/002081897550447.

Moyo, Last. From Sudan to Zimbabwe, China is Part of the Problem, 2009.

Mueller, John E. “Trends in Popular Support for the Wars in Korea and Vietnam.” The American Political Science Review 65, no. 2 (1971): 358–75. https://doi.org/10.2307/1954454.

Munck, Gerardo L., and Jay Verkuilen. “Conceptualizing and Measuring Democracy: Evaluating Alternative Indices.” Comparative Political Studies 35, no. 1 (February 2002): 5–34. https://doi.org/10.1177/001041400203500101.

Murphy, Sean D. Humanitarian Intervention : The United Nations in an Evolving World Order. Procedural Aspects of International Law Series ; v. 21; Procedural Aspects of International Law Series ; v. 21., Book, Whole. Philadelphia: University of Pennsylvania Press, 1996. http://search.trln.org/search?id=DUKE002213766.

Murray, Patrick. “A Question of Age: Measuring Attitudes about an Unknown Fact.” Survey Practice 4, no. 6 (December 12, 2011). https://www.surveypractice.org/article/3855.

Mutua, Makau. “Savages, Victims, and Saviors: The Metaphor of Human Rights.” Harvard International Law Journal 42, no. 1 (2001): 201–46.

Nance, Mark T.and Sarah Lycan M.S.S. A Stimulating Debate: Explaining US and European Responses to the Financial Crisis., n.d.

Nedelsky, Nadya. “The Implications of the Civic Model of Sovereignty in the Czech Republic.” In Defining the Sovereign Community: The Czech and Slovak Republics, 231–75. University of Pennsylvania Press, 2012.

Neudorfer, Kelly. Sexual Exploitation and Abuse in UN Peacekeeping: An Analysis of Risk and Prevention Factors. Lanham, MD: Lexington Books, 2015. http://UCI.eblib.com/patron/FullRecord.aspx?p=1913799.

Nickel, James W. “What’s Wrong with Ethnic Cleansing?1.” Journal of Social Philosophy 26, no. 1 (1995): 5–15. https://doi.org/10.1111/j.1467-9833.1995.tb00054.x.

Nisbett, Richard E., and Timothy D. Wilson. “Telling More than We Can Know: Verbal Reports on Mental Processes.” Psychological Review 84, no. 3 (1977): 231–59. https://doi.org/10.1037/0033-295X.84.3.231.

Nmehielle, Vincent O. “A Just World Under Law: An African Perspective on the Status of the Individual in International Law.” Proceedings of the Annual Meeting (American Society of International Law) 100 (2006): 252–57.

Nordås, Ragnhild, and Siri C. A. Rustad. “Sexual Exploitation and Abuse by Peacekeepers: Understanding Variation.” International Interactions 39, no. 4 (September 1, 2013): 511–34. https://doi.org/10.1080/03050629.2013.805128.

North, Douglass C., John Joseph Wallis, and Barry R. Weingast. “Violence and the Rise of Open-Access Orders.” Journal of Democracy 20, no. 1 (January 31, 2009): 55–68. https://doi.org/10.1353/jod.0.0060.

Notar, Susan A. “Peacekeepers as Perpetrators: Sexual Exploitation and Abuse of Women and Children in the Democratic Republic of the Congo.” Am. UJ Gender Soc. Pol’y & L. 14 (2006): 413.

Nunn, Nathan, and Leonard Wantchekon. “The Slave Trade and the Origins of Mistrust in Africa.” The American Economic Review 101, no. 7 (2011): 3221–52. https://doi.org/10.1257/aer.101.7.3221.

“Nunn_Wantchekon_2011_The Slave Trade and the Origins of Mistrust in Africa.Pdf,” n.d.

Oana, Ioana-Elena, Carsten Q. Schneider, and Eva Thomann. “Calibration and Concept Formation.” In A Beginner’s Guide to Qualitative Comparative Analysis (QCA) Using R, Forthcoming.

Obiora, L. Amede. “Bridges and Barricades: Rethinking Polemics and Intransigence in the Campaign against Female Circumcision Colloquium: Bridging Society, Culture, and Law: The Issue of Female Circumcision.” Case Western Reserve Law Review 47, no. 2 (1996): 275–378.

O’Brien, Kevin J., and Lianjiang Li. “Popular Contention and Its Impact in Rural China.” Comparative Political Studies 38, no. 3 (April 2005): 235–59. https://doi.org/10.1177/0010414004272528.

O’Brien, Robert, and Marc Williams. Global Political Economy: Evolution and Dynamics. 3rd ed. New York: Palgrave Macmillan, 2010.

“O’Brien_Li_2005_Popular Contention and Its Impact in Rural China.Pdf,” n.d.

Odello, Marco, and Róisín Burke. “Between Immunity and Impunity: Peacekeeping and Sexual Abuses and Violence.” The International Journal of Human Rights 20, no. 6 (August 17, 2016): 839–53. https://doi.org/10.1080/13642987.2016.1176810.

Odgaard, Liselotte. “Preparing for an Imperfect World,” n.d., 10.

Oko, Okechukwu. “Confronting Transgressions of Prior Military Regimes Towards a More Pragmatic Approach.” Cardozo Journal of International and Comparative Law 11, no. 1 (2004 2003): 89–142.

Olson, Mancur. The Logic of Collective Action; Public Goods and the Theory of Groups. Harvard Economic Studies, v. 124. Cambridge, Mass: Harvard University Press, 1971. https://uci.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma991020641559704701&context=L&vid=01CDL_IRV_INST:UCI&search_scope=MyInst_and_CI&tab=Everything&lang=en.

———. The Rise and Decline of Nations: Economic Growth, Stagflation, and Social Rigidities. New Haven: Yale University Press, 1982.

Omach, Paul. “The African Crisis Response Initiative: Domestic Politics and Convergence of National Interests.” African Affairs 99, no. 394 (2000): 73–95.

Omer, A. “Modernists Despite Themselves: The Phenomenology of the Secular and the Limits of Critique as an Instrument of Change.” Journal of the American Academy of Religion 83, no. 1 (March 1, 2015): 27–71. https://doi.org/10.1093/jaarel/lfu081.

Oppenheimer, Joe A. Principles of Politics: A Rational Choice Theory Guide to Politics and Social Justice. Cambridge: Cambridge University Press, 2012.

Orfeo, Fioretos. “The Domestic Sources of Multilateral Preferences: Varieties of Capitalism in the European Community.” In Varieties of Capitalism: The Institutional Foundations of Comparative Advantage, edited by Peter A. Hall and David W. Soskice, 213–44. Oxford [England] ; New York: Oxford University Press, 2001.

Orford, Anne. “Lawful Authority and the Responsibility to Protect.” In Legality and Legitimacy in Global Affairs, edited by Richard Falk, Mark Juergensmeyer, and Vesselin Popovski, 248–72. Oxford University Press, 2011.

Osiatyński, Wiktor. “Rights and Cultures.” In Human Rights and Their Limits, 144–86. Cambridge: Cambridge University Press, 2009. https://doi.org/10.1017/CBO9780511808333.005.

Ostrom, Elinor. “A Behavioral Approach to the Rational Choice Theory of Collective Action: Presidential Address, American Political Science Association, 1997.” American Political Science Review 92, no. 1 (March 1998): 1–22. https://doi.org/10.2307/2585925.

———. “Collective Action and the Evolution of Social Norms.” Journal of Economic Perspectives 14, no. 3 (August 2000): 137–58. https://doi.org/10.1257/jep.14.3.137.

———. Governing the Commons: The Evolution of Institutions for Collective Action. Book, Whole. Cambridge university press, 1990.

Panitch, Leo. “Throughly Modern Marx.” Foreign Policy, no. 172 (2009): 140–45.

Paolacci, Gabriele. “Running Experiments on Amazon Mechanical Turk.” Judgment and Decision Making 5, no. 5 (2010): 411–419.

Paris, Roland. “International Peacebuilding and the ‘Mission Civilisatrice.’” Review of International Studies 28, no. 4 (2002): 637–56.

Park, Cheol Hee. “Historical Memory and the Resurgence of Nationalism: A Korean Perspective.” In East Asia’s Haunted Present: Historical Memories and the Resurgence of Nationalism, edited by Tsuyoshi Hasegawa and Kazuhiko Tōgō, 190–203. PSI Reports (Westport, Conn.). Westport, Conn: Praeger Security International, 2008.

Park, Susan. “The World Bank Group: Championing Sustainable Development Norms?” Global Governance 13, no. 4 (2007): 535–56. https://doi.org/10.1163/19426720-01304007.

Parks, Bradley C., and J. Timmons Roberts. “Inequality and the Global Climate Regime: Breaking the North-South Impasse.” Cambridge Review of International Affairs 21, no. 4 (December 1, 2008): 621–48. https://doi.org/10.1080/09557570802452979.

“Part 1. State Projects of Legibility and Simplification,” n.d.

“Part 2. Transforming Visions,” n.d.

“Part II Outcomes of Social Revolutions in France, Russia, and China,” n.d.

“PART ONE: Revolutionary Origins of Capitalist Democracy,” n.d.

“PART THREE: Theoretical Implications and Projections,” n.d.

Patrick, Stewart. The Sovereignty Wars: Reconciling America with the World. Washington, D.C: Brookings Institution Press, 2018. http://www.jstor.org/stable/10.7864/j.ctt1vjqpvc.

Pauwelyn, Joost. “The Role of Public International Law in the WTO: How Far Can We Go?” The American Journal of International Law 95, no. 3 (July 2001): 535. https://doi.org/10.2307/2668492.

Peou, Sorpong. Peace and Security in the Asia-Pacific : Theory and Practice. Book, Whole. Santa Barbara, Calif.: Praeger Security International, 2010.

Perek, L. “Planetary Protection: Lessons Learned.” Advances in Space Research 34, no. 11 (2004): 2368–70. https://doi.org/10.1016/j.asr.2003.02.066.

Perry, Michael J. “Are Human Rights Universal?” In The Idea of Human Rights: Four Inquiries, 57–86. Oxford University Press, 2000.

Peterson, Spike V. “How (the Meaning of) Gender Matters in Political Economy.” New Political Economy 10, no. 4 (December 2005): 499–521. https://doi.org/10.1080/13563460500344468.

Philpott, Daniel. “The Religious Roots of Modern International Relations.” World Politics 52, no. 2 (January 2000): 206–45. https://doi.org/10.1017/S0043887100002604.

Piana, Daniela. Judicial Accountabilities in New Europe: From Rule of Law to Quality of Justice. Studies in Modern Law and Policy. Farnham, England ; Burlington, Vt: Ashgate, 2010. https://books.google.com/books/about/Judicial_Accountabilities_in_New_Europe.html?id=8odIt9g9EwUC.

Pierson, Christopher. “Globalization and the End of Social Democracy.” In Hard Choices: Social Democracy in the Twenty-First Century, 64–89. Cambridge, UK : Malden, MA: Polity Press ; Blackwell Publishers, 2001.

Pierson, Paul. “Increasing Returns, Path Dependence, and the Study of Politics.” American Political Science Review 94, no. 2 (2000): 251–67. https://doi.org/10.2307/2586011.

———. “The New Politics of the Welfare State.” World Politics 48, no. 2 (January 1996): 143–79. https://doi.org/10.1353/wp.1996.0004.

Pollack, Mark A. “Delegation, Agency, and Agenda Setting in the European Community.” International Organization 51, no. 1 (1997): 99–134. https://doi.org/10.1162/002081897550311.

Pop-Eleches, Grigore. “Communist Development and the Post-Communist Democratic Deficit.” In Historical Legacies of Communism in Russia and Eastern Europe, edited by Mark Beissinger and Stephen Kotkin, 28–51. Cambridge University Press, 2014.

“Pop-Eleches_2014_Communist Development and the Post-Communist Democratic Deficit.Pdf,” n.d.

Popovski, Vesselin. “Legality and Legitimacy of International Criminal Tribunals.” In Legality and Legitimacy in Global Affairs, edited by Richard A. Falk, Mark Juergensmeyer, and Vesselin Popovski, 388–413. New York: Oxford University Press, 2012. http://search.trln.org.prox.lib.ncsu.edu/search?id=DUKE005323147;

Porsdam, Helle. “Divergent Transatlantic Views on Human Rights: Economic, Social and Cultural Rights.” In From Civil to Human Rights: Dialogues on Law and Humanities in the United States and Europe, 92–113. Edward Elgar Publishing, 2009.

Přibáň, Jiří. “Judicial Power vs. Democratic Representation: The Culture of Constitutionalism and Human Rights in the Czech Legal System.” In Constitutional Justice, East and West: Democratic Legitimacy and Constitutional Courts in Post-Communist Europe in a Comparative Perspective, edited by Wojciech Sadurski, 373–394. Springer Science & Business Media, 2002.

Przeworski, Adam, Limongi Neto, and Fernando Papaterra. “Modernization: Theories and Facts.” World Politics 49, no. 2 (January 1997): 155–83. https://doi.org/10.1353/wp.1997.0004.

“Przeworski et Al_1997_Modernization.Pdf,” n.d.

“Przeworski et Al_1997_Modernization.Pdf,” n.d.

Putnam, Robert D. “Diplomacy and Domestic Politics: The Logic of Two-Level Games.” International Organization 42, no. 3 (1988): 427–60. https://doi.org/10.1017/S0020818300027697.

———. “Tuning In, Tuning Out: The Strange Disappearance of Social Capital in America.” PS: Political Science and Politics 28, no. 4 (1995): 664–83. https://doi.org/10.2307/420517.

Putnam, Robert D, Robert Leonardi, and Raffaella Y Nanetti. “Explaining Institutional Performance.” In Making Democracy Work: Civic Traditions in Modern Italy., 83–120. Princeton; Ewing: Princeton University Press California Princeton Fulfillment Services [distributor, 1994. http://search.ebscohost.com/direct.asp?db=sih&jid=8W0G&scope=site.

———. “Introduction: Studying Institutional Performance.” In Making Democracy Work: Civic Traditions in Modern Italy., 5–16. Princeton; Ewing: Princeton University Press California Princeton Fulfillment Services [distributor, 1994. http://search.ebscohost.com/direct.asp?db=sih&jid=8W0G&scope=site.

———. Making Democracy Work: Civic Traditions in Modern Italy. Princeton; Ewing: Princeton University Press California Princeton Fulfillment Services [distributor, 1994. http://search.ebscohost.com/direct.asp?db=sih&jid=8W0G&scope=site.

———. “Social Capital and Institutional Success.” In Making Democracy Work: Civic Traditions in Modern Italy., 165–85. Princeton; Ewing: Princeton University Press California Princeton Fulfillment Services [distributor, 1994. http://search.ebscohost.com/direct.asp?db=sih&jid=8W0G&scope=site.

———. “Tracing the Roots of the Civic Community.” In Making Democracy Work: Civic Traditions in Modern Italy., 121–62. Princeton; Ewing: Princeton University Press California Princeton Fulfillment Services [distributor, 1994. http://search.ebscohost.com/direct.asp?db=sih&jid=8W0G&scope=site.

“Putnam_1995_Tuning In, Tuning Out.Pdf,” n.d.

Pye, Lucian W. “Culture as Destiny.” In Political Culture in Post-Communist Europe : Attitudes in New Democracies, edited by Detlef Pollack, Jörg Jacobs, Olaf Müller, and Gert Pickel, 15–15. Aldershot: Ashgate, 2003. http://www2.lib.ncsu.edu/catalog/record/NCSU1667150.

Ragin, Charles C. Redesigning Social Inquiry: Fuzzy Sets and Beyond. University of Chicago Press, 2008.

Ratner, Steven R. “The Security Council and International Law.” In The UN Security Council: From the Cold War to the 21st Century, edited by David Malone, 591–605. Lynne Rienner Publishers, 2004.

Rayroux, Antoine. “Beyond Actorness in EU Crisis Management: Internal Functions of External Peacekeeping.” Journal of European Integration 35, no. 7 (November 1, 2013): 731–48. https://doi.org/10.1080/07036337.2012.728212.

Regan, Patrick M., and Aysegul Aydin. “Diplomacy and Other Forms of Intervention in Civil Wars.” Journal of Conflict Resolution 50, no. 5 (October 2006): 736–56. https://doi.org/10.1177/0022002706291579.

Reich, Robert B. “The Decline of Public Investment.” In The Work of Nations: Preparing Ourselves for 21st Century Capitalis, 252–61. Knopf Doubleday Publishing Group, 2010.

———. “The Problem Restated.” In The Work of Nations: Preparing Ourselves for 21st Century Capitalis, 243–51. Knopf Doubleday Publishing Group, 2010.

———. “The Uses of Vestigial Thought.” In The Work of Nations: Preparing Ourselves for 21st Century Capitalis, 262–300. Knopf Doubleday Publishing Group, 2010.

———. “Who Is ‘Us’?” In The Work of Nations: Preparing Ourselves for 21st Century Capitalis, 301–15. Knopf Doubleday Publishing Group, 2010.

Reus-Smit, Christian, ed. The Politics of International Law. Cambridge Studies in International Relations 96. Cambridge, UK ; New York: Cambridge University Press, 2004. http://search.trln.org/search?id=NCSU1735500; Get an online version (NCCU only) (http://www.loc.gov/catdir/toc/cam041/2003065412.html).

Riker, William H. Liberalism against Populism: A Confrontation between the Theory of Democracy and the Theory of Social Choice. Prospect Heights, Ill: Waveland Press, 1988.

Rodrik, Dani. “Sense and Nonsense in the Globalization Debate.” Foreign Policy, no. 107 (1997): 19. https://doi.org/10.2307/1149330.

Rohlfing, Ingo. “What You See and What You Get: Pitfalls and Principles of Nested Analysis in Comparative Research.” Comparative Political Studies 41, no. 11 (November 2008): 1492–1514. https://doi.org/10.1177/0010414007308019.

Rosecrance, Richard N., and Steven E. Miller, eds. The Next Great War?: The Roots of World War I and the Risk of U.S.-China Conflict. The MIT Press, 2014. https://doi.org/10.7551/mitpress/9780262028998.001.0001.

Rosenberg, Shawn W. The Not so Common Sense: Differences in How People Judge Social and Political Life. Yale University Press, 2008.

Rosenfeld, Michel. “The Rule of Law and the Legitimacy of Constitutional Democracy.” SSRN Electronic Journal, 2001. https://doi.org/10.2139/ssrn.262350.

Rosenthal, Seth A. “Poll Produces Eye-Popping Headline: Questionable Inferences Serve as Prop to Turn Public Perception on Its Head.” Survey Practice 4, no. 6 (December 1, 2011): 1–5. https://doi.org/10.29115/SP-2011-0032.

Ross, Carne. Independent Diplomat : Dispatches from an Unaccountable Elite. Crises in World Politics, Book, Whole. Ithaca, N.Y.: Cornell University Press, 2007. http://search.trln.org/search?id=UNCb5188534.

Rousseau, Jean-Jacques. The Social Contract & Discourses. Translated by G. D. H. (George Douglas Howard) Cole, 2014. http://www.gutenberg.org/ebooks/46333.

Ruggie, John Gerard. “International Regimes, Transactions, and Change: Embedded Liberalism in the Postwar Economic Order.” International Organization 36, no. 2 (April 1982): 379–415. https://doi.org/10.1017/S0020818300018993.

Rüland, Jürgen. “Southeast Asian Regionalism and Global Governance: ‘Multilateral Utility’ or ‘Hedging Utility’?” Contemporary Southeast Asia: A Journal of International and Strategic Affairs 33, no. 1 (2011): 83–112. https://doi.org/10.1355/cs33-1d.

———. “The Rise of ‘Diminished Multilaterism:’ East Asian and European Forum Shopping in Global Governance.” In Understanding the Dynamics of Global Inequality, edited by Alexander Lenger and Florian Schumacher, 159–77. Springer Berlin Heidelberg, 2015. https://doi.org/10.1007/978-3-662-44766-6_8.

Russett, Bruce. “Liberalism.” In International Relations Theories, edited by Tim Dunne, Milja Kurki, and Steve Smith, Third edition., 94–113. Oxford: Oxford University Press, 2013.

Rynning, Sten. NATO in Afghanistan: The Liberal Disconnect. Redwood City, UNITED STATES: Stanford University Press, 2012. http://ebookcentral.proquest.com/lib/uci/detail.action?docID=997335.

Sachs, Jeffrey. “Ending Poverty Traps.” In Common Wealth: Economics for a Crowded Planet. Penguin, 2008.

Sanders, Luk. “The Strange Belief of Alexis de Tocqueville: Christianity as Philosophy.” International Journal of Philosophy and Theology 74, no. 1 (March 2013): 33–53. https://doi.org/10.1080/21692327.2013.771481.

Sandholtz, Wayne, and Alec Stone Sweet. “Law, Politics, and International Governance.” In The Politics of International Law, edited by Christian Reus-Smit, 238–71. Cambridge Studies in International Relations 96. Cambridge, UK ; New York: Cambridge University Press, 2004. http://search.trln.org/search?id=NCSU1735500; Get an online version (NCCU only) (http://www.loc.gov/catdir/toc/cam041/2003065412.html).

Santiago, Jose. “From ‘Civil Religion’ to Nationalism as the Religion of Modern Times: Rethinking a Complex Relationship.” Journal for the Scientific Study of Religion 48, no. 2 (2009): 394–401. https://doi.org/10.1111/j.1468-5906.2009.01455.x.

Sartori, Giovanni. “Concept Misformation in Comparative Politics.” American Political Science Review 64, no. 4 (December 1970): 1033–53. https://doi.org/10.2307/1958356.

Schelling, Thomas C. Micromotives and Macrobehavior. W. W. Norton & Company, 2006.

Schildkraut, Deborah J. “The Dynamics of Public Opinion on Ethnic Profiling After 9/11: Results From a Survey Experiment.” American Behavioral Scientist 53, no. 1 (September 2009): 61–79. https://doi.org/10.1177/0002764209338786.

Schlesinger, Stephen C. Act of Creation: The Founding of the United Nations: A Story of Superpowers, Secret Agents, Wartime Allies and Enemies, and Their Quest for a Peaceful World. Boulder, Colo: Westview Press, 2003.

Schmitter, Philippe C. “Ernst B. Haas and the Legacy of Neofunctionalism.” Journal of European Public Policy 12, no. 2 (April 2005): 255–72. https://doi.org/10.1080/13501760500043951.

Schnapper, Dominique, Pascale Krief, and Emmanuel Peignard. “French Immigration and Integration Policy: A Complex Combination.” In The Integration of Immigrants in European Societies: National Differences and Trends of Convergence, edited by Friedrich Heckmann and Dominique Schnapper, 15–44. Lucius & Lucius DE, 2003.

Schrodt, Philip A. “Seven Deadly Sins of Contemporary Quantitative Political Analysis.” Journal of Peace Research 51, no. 2 (March 2014): 287–300. https://doi.org/10.1177/0022343313499597.

Schuknecht, Ludger, Philippe Moutot, Philipp Rother, and Jürgen Stark. “The Stability and Growth Pact: Crisis and Reform,” n.d., 23.

Schuman, Howard, and Jacqueline Scott. “Problems in the Use of Survey Questions to Measure Public Opinion.” Science 236, no. 4804 (1987): 957–59.

Schwartz, Herman. “Eastern Europe’s Constitutional Courts.” Journal of Democracy 9, no. 4 (1998): 100–114. https://doi.org/10.1353/jod.1998.0070.

Schwarz, Tanya B., and Cecelia Lynch. “Religion in International Relations.” In Oxford Research Encyclopedia of Politics, by Tanya B. Schwarz and Cecelia Lynch. Oxford University Press, 2016. https://doi.org/10.1093/acrefore/9780190228637.013.122.

Schweller, Randall L., and Xiaoyu Pu. “After Unipolarity: China’s Visions of International Order in an Era of U.S. Decline.” International Security 36, no. 1 (July 2011): 41–72. https://doi.org/10.1162/ISEC_a_00044.

Scott, James C. Seeing Like a State: How Certain Schemes to Improve the Human Condition Have Failed. Yale University Press, 1998.

Scott, Shirley, Anne-Marie Slaughter, and Friedrich Kratochwil. “Legalization: Interpreting the Empirical Evidence.” Proceedings of the Annual Meeting (American Society of International Law) 96 (2002): 291–98. https://doi.org/10.1017/S0272503700063588.

“Scott_1998_Seeing Like a State.Pdf,” n.d.

Seawright, Jason. “Better Multimethod Design:The Promise of Integrative Multimethod Research.” Security Studies 25, no. 1 (January 2, 2016): 42–49. https://doi.org/10.1080/09636412.2016.1134187.

———. Multi-Method Social Science: Combining Qualitative and Quantitative Tools. Strategies for Social Inquiry. Cambridge, UK: Cambridge University Press, 2016.

———. “The Case for Selecting Cases That Are Deviant or Extreme on the Independent Variable.” Sociological Methods & Research 45, no. 3 (August 2016): 493–525. https://doi.org/10.1177/0049124116643556.

Seawright, Jason, and John Gerring. “Case Selection Techniques in Case Study Research: A Menu of Qualitative and Quantitative Options.” Political Research Quarterly 61, no. 2 (June 2008): 294–308. https://doi.org/10.1177/1065912907313077.

Sestanovich, Stephen. Maximalist: America in the World from Truman to Obama. 1 edition. Vintage, 2014.

Shared Vision, Common Action: A Stronger Europe: A Global Strategy for the European Union’s Foreign and Security Policy. Luxembourg: Publications Office of the European Union, 2016. https://europa.eu/globalstrategy/sites/globalstrategy/files/regions/files/eugs_review_web_0.pdf.

Sharman, J. C. “Blacklisting.” In The Money Laundry: Regulating Criminal Finance in the Global Economy, 99–130. Cornell University Press, 2011.

———. “Socialization and Competition.” In The Money Laundry: Regulating Criminal Finance in the Global Economy, 131–64. Cornell University Press, 2011.

Sheikh, Mona Kanwal. “Religion, Emotions and Conflict Escalation.” In Routledge Handbook of Ethics and International Relations, edited by Brent J. Steele and Eric A. Heinze, 1st ed., 518–26. Abingdon, Oxon ; New York, NY : Routledge, 2018.: Routledge, 2018. https://doi.org/10.4324/9781315725932-43.

Shelton, Dinah. “Normative Hierarchy in International Law.” American Journal of International Law 100, no. 2 (April 2006): 291–323. https://doi.org/10.1017/S0002930000016675.

Shi, Leiyu, Douglas A. Singh, and Jenna Tsai. “The Changing U.S. Health System.” In Comparative Health Systems, edited by James A. Johnson and Carleen H. Stoskopf, 367–86. Jones & Bartlett Publishers, 2010.

Shin, Doh Chull. “On the Third Wave of Democratization: A Synthesis and Evaluation of Recent Theory and Research.” World Politics 47, no. 1 (October 1994): 135–70. https://doi.org/10.2307/2950681.

Shlapentokh, Dmitry. “The Russian Approach to Human Rights Intervention.” Contemporary Review 278, no. 1622 (March 2001): 156–58.

Sides, John, and Kimberly Gross. “Stereotypes of Muslims and Support for the War on Terror.” The Journal of Politics 75, no. 3 (July 2013): 583–98. https://doi.org/10.1017/S0022381613000388.

Sikkink, Kathryn. The Justice Cascade: How Human Rights Prosecutions Are Changing World Politics. 1st ed. New York: W. W. Norton & Co, 2011.

Sil, Rudra, and Peter J. Katzenstein. Beyond Paradigms: Analytic Eclecticism in the Study of World Politics. Palgrave Macmillan, 2010.

Simić, Olivera. “Does the Presence of Women Really Matter? Towards Combating Male Sexual Violence in Peacekeeping Operations.” International Peacekeeping 17, no. 2 (April 1, 2010): 188–99. https://doi.org/10.1080/13533311003625084.

Simic, Olivera. Regulation of Sexual Conduct in UN Peacekeeping Operations. Berlin ; New York: Springer, 2012. http://dx.doi.org/10.1007/978-3-642-28484-7.

———. “Who Should Be a Peacekeeper?” Peace Review 21, no. 3 (September 1, 2009): 395–402. https://doi.org/10.1080/10402650903099492.

Simić, Olivera, and Melanie O’Brien. “‘Peacekeeper Babies’: An Unintended Legacy of United Nations Peace Support Operations.” International Peacekeeping 21, no. 3 (May 27, 2014): 345–63. https://doi.org/10.1080/13533312.2014.938581.

Simmons, Beth A. “The International Politics of Harmonization: The Case of Capital Market Regulation.” International Organization 55, no. 3 (2001): 589–620. https://doi.org/10.1162/00208180152507560.

Simon, Jeffrey. “The ESDP between Washington and Brussels.” In European Security and Defence Policy : An Implementation Perspective, edited by Michael Merlingen and Rasa Ostrauskaite, 158–72. Routledge Advances in European Politics. London ;New York: Routledge, 2008.

Simpser, Alberto, Dan Slater, and Jason Wittenberg. “Dead But Not Gone: Contemporary Legacies of Communism, Imperialism, and Authoritarianism.” Annual Review of Political Science 21, no. 1 (May 11, 2018): 419–39. https://doi.org/10.1146/annurev-polisci-062615-020900.

“Simpser et Al_2018_Dead But Not Gone.Pdf,” n.d.

Skak, Mette. “Russian Strategic Culture: The Role of Today’s Chekisty.” Contemporary Politics 22, no. 3 (July 2, 2016): 324–41. https://doi.org/10.1080/13569775.2016.1201317.

Sklair, Leslie. “Democracy and the Transnational Capitalist Class.” Annals of the American Academy of Political and Social Science 581 (2002): 144–57.

Skocpol, Theda. States and Social Revolutions: A Comparative Analysis of France, Russia, and China. Canto classics edition. Canto Classics. Cambridge: Cambridge University Press, 2015.

Skocpol, Theda, Marjorie Abend-Wein, Christopher Howard, and Susan Goodrich Lehmann. “Women’s Associations and the Enactment of Mothers’ Pensions in the United States.” American Political Science Review 87, no. 3 (1993): 686–701. https://doi.org/10.2307/2938744.

“Skocpol_2015_States and Social Revolutions.Pdf,” n.d.

Slater, Dan. Ordering Power: Contentious Politics and Authoritarian Leviathans in Southeast Asia. Cambridge Studies in Comparative Politics. Cambridge ; New York: Cambridge University Press, 2010.

“Slater_2010_Ordering Power.Pdf,” n.d.

“Slater_2010_Ordering Power.Pdf,” n.d.

Slaughter, Anne-Marie. The Chessboard and the Web: Strategies of Connection in a Networked World. The Henry L. Stimson Lectures Series. New Haven: Yale University Press, 2017.

———. “The Real New World Order.” Foreign Affairs 76, no. 5 (1997): 183–97. https://doi.org/10.2307/20048208.

Smith, Alastair, and Allan C. Stam. “Bargaining and the Nature of War.” Journal of Conflict Resolution 48, no. 6 (December 2004): 783–813. https://doi.org/10.1177/0022002704268026.

Smith, Michael E. “The European External Action Service and the Security–Development Nexus: Organizing for Effectiveness or Incoherence?” Journal of European Public Policy 20, no. ahead-of-print (2013): 1–17.

———. “Transatlantic Security Relations since the European Security Strategy: What Role for the EU in Its Pursuit of Strategic Autonomy?” Journal of European Integration 40, no. 5 (July 29, 2018): 605–20. https://doi.org/10.1080/07036337.2018.1488840.

Smithey, Shannon Ishiyama, and John Ishiyama. “Judicial Activism in Post-Communist Politics.” Law & Society Review 36, no. 4 (2002): 719–42. https://doi.org/10.2307/1512169.

———. “Judicious Choices: Designing Courts in Post-Communist Politics.” Communist and Post-Communist Studies 33, no. 2 (2000): 163–82. https://doi.org/10.1016/S0967-067X(00)00002-7.

Smolens, Susan. “Violence against Women: Consciousness and Law in Four Central European Emerging Democracies - Poland, Hungary, Slovakia, and the Czech Republic.” Tulane European & Civil Law Forum 15/16 (2001 2000): 1–42.

Snyder, Jack L. “The Soviet Strategic Culture. Implications for Limited Nuclear Operations. R-2154-AF.” RAND CORP SANTA MONICA CALIF, 1977.

Sobel, Beverly G., Armin Rosencranz, and Isaac Smith. “The Melting and Partitioning of a Global Commons Other International Developments: Arctic/UNCLOS.” Environmental Policy and Law 37, no. 6 (2007): 467–70.

Solingen, Etel. “Domestic Coalitions, Internationalization, and War: Then and Now.” International Security 39, no. 1 (August 29, 2014): 44–70.

———. “East Asian Regional Institutions: Characteristics, Sources, Distinctiveness.” In Remapping East Asia: The Construction of a Region, edited by Thomas J. Pempel, 31–53. Cornell University Press, 2005.

———. Nuclear Logics: Contrasting Paths in East Asia and the Middle East. Princeton Studies in International History and Politics. Princeton: Princeton University Press, 2007.

———. “Pax Asiatica versus Bella Levantina: The Foundations of War and Peace in East Asia and the Middle East.” American Political Science Review 101, no. 4 (November 2007): 757–80. https://doi.org/10.1017/S0003055407070487.

———. “The Genesis, Design and Effects of Regional Institutions: Lessons from East Asia and the Middle East.” International Studies Quarterly 52, no. 2 (June 2008): 261–94. https://doi.org/10.1111/j.1468-2478.2008.00501.x.

Solingen, Etel, and Peter Gourevitch. “Domestic Coalitions: International Sources and Effects” 1 (September 26, 2017). https://doi.org/10.1093/acrefore/9780190228637.013.353.

Spencer, Sarah W. “Making Peace: Preventing and Responding to Sexual Exploitation by United Nations Peacekeepers.” Journal of Public and International Affairs 16, no. 1 (2005): 167–81.

Springs, Jason A. “Tentacles of the Leviathan? Nationalism, Islamophobia, and the Insufficiency-yet-Indispensability of Human Rights for Religious Freedom in Contemporary Europe.” Journal of the American Academy of Religion 84, no. 4 (December 2016): 903–36. https://doi.org/10.1093/jaarel/lfw021.

Spruyt, Hendrik. The Sovereign State and Its Competitors: An Analysis of Systems Change. Princeton Studies in International History and Politics. Princeton, NJ: Princeton Univ. Press, 1996.

Stacy, Helen. “Humanitarian Intervention and Relational Sovereignty.” In Intervention, Terrorism, and Torture : Contemporary Challenges to Just War Theory, edited by Steven Lee, 89–104. AMINTAPHIL: The Philosophical Foundations of Law and Justice ; v. 1; AMINTAPHIL ; v. v. 1. Dordrecht: Springer, 2007. http://search.trln.org/search?id=NCCU444883.

Stanton, Gregory. “The Rwandan Genocide: Why Early Warning Failed.” Journal of African Conflicts and Peace Studies 1, no. 2 (November 28, 2012). http://dx.doi.org/10.5038/2325-484X.1.2.1.

Steinberg, Richard H. “Trade-Environment Negotiations in the EU, NAFTA, and WTO: Regional Trajectories of Rule Development.” The American Journal of International Law 91, no. 2 (April 1997): 231–67. https://doi.org/10.2307/2954211.

Steinmo, Sven. “Historical Institutionalism.” In Approaches and Methodologies in the Social Sciences: A Pluralist Perspective, edited by Donatella Della Porta and Michael Keating, 118–38. Cambridge: Cambridge University Press, 2008. http://search.trln.org/search?id=DUKE004053254.

Sterling-Folker, Jennifer. “Neoliberalism.” In International Relations Theories, edited by Tim Dunne, Milja Kurki, and Steve Smith, Third edition., 114–30. Oxford: Oxford University Press, 2013.

Stiglitz, Joseph E. “Democratizing the International Monetary Fund and the World Bank: Governance and Accountability.” Governance 16, no. 1 (January 2003): 111–39. https://doi.org/10.1111/1468-0491.00207.

———. “The Future of Global Governance.” In The Washington Consensus Reconsidered: Towards a New Global Governance, edited by Narcís Serra and Joseph E. Stiglitz, 309–23. The Initiative for Policy Dialogue Series. Oxford: Oxford University Press, 2008. http://www2.lib.ncsu.edu/catalog/record/UNCb5685399.

Stoskopf, Carleen H., and James A. Johnson. “Introduction to Health Systems.” In Comparative Health Systems, edited by James A. Johnson and Carleen H. Stoskopf, 3–15. Jones & Bartlett Publishers, 2010.

Stoyanov, Dragomir, and Justyna Pierzynska. “Bulgarian Strategic Culture between Europe and Russia Past and Present.” In Strategic Culture in Russia’s Neighborhood, edited by Hanna Smith, 1st ed., 141–62. United States: Lexington Books, 2019.

Strayer, Joseph R. On the Medieval Origins of the Modern State. Princeton University Press, 1970.

Streeck, Wolfgang, and Anke Hassel. “The Crumbling Pillars of Social Partnership.” West European Politics 26, no. 4 (October 2003): 101–24. https://doi.org/10.1080/01402380312331280708.

Strolovitch, Dara Z. “Do Interest Groups Represent the Disadvantaged? Advocacy at the Intersections of Race, Class, and Gender.” Journal of Politics 68, no. 4 (2006): 894–910. https://doi.org/10.1111/j.1468-2508.2006.00478.x.

Strøm, Kaare. “Delegation and Accountability in Parliamentary Democracies.” European Journal of Political Research 37, no. 3 (2000): 261–89. https://doi.org/10.1111/1475-6765.00513.

Subotić, Jelena. “The Politics of Hijacked Justice.” In Hijacked Justice: Dealing with the Past in the Balkans, 15–37. Cornell University Press, 2011.

Suhrke, Astri. “A Contradictory Mission? NATO from Stabilization to Combat in Afghanistan.” International Peacekeeping 15, no. 2 (April 2008): 214–36. https://doi.org/10.1080/13533310802041477.

Sweet, Alec Stone. “Judicialization and the Construction of Governance.” Comparative Political Studies 32, no. 2 (1999): 147–84. https://doi.org/10.1177/0010414099032002001.

Talbot, John M. “Tropical Commodity Chains, Forward Integration Strategies and International Inequality: Coffee, Cocoa and Tea.” Review of International Political Economy 9, no. 4 (November 2002): 701–34. https://doi.org/10.1080/0969229022000021862.

Taliaferro, Jeffrey W. “Security Seeking under Anarchy: Defensive Realism Revisited.” International Security 25, no. 3 (2000): 128–61. https://doi.org/10.1162/016228800560543.

Tan, Celine. “Reform or Reinvent? The IMF at a Crossroads.” Global Governance: A Review of Multilateralism and International Organizations 12, no. 4 (August 3, 2006): 507–22. https://doi.org/10.1163/19426720-01204011.

Tang, C.-M. “Southeast Asian Peace Revisited: A Capitalist Trajectory.” International Relations of the Asia-Pacific 12, no. 3 (September 1, 2012): 389–417. https://doi.org/10.1093/irap/lcs009.

Tang, Shiping. The Social Evolution of International Politics. 1st ed. Oxford: Oxford University Press, 2013.

Tarrow, Sidney. “Bridging the Quantitative-Qualitative Divide.” In Rethinking Social Inquiry: Diverse Tools, Shared Standards, edited by Henry E. Brady and David Collier, 2nd ed., 101–10. Lanham, Md: Rowman & Littlefield Publishers, 2010.

Taylor, Rupert. “The Injustice of a Consociational Solution to the Northern Ireland Problem.” In Consociational Theory : McGarry and O’Leary and the Northern Ireland Conflict, edited by Rupert Taylor. Routledge, 2009. https://doi.org/10.4324/9780203962565.

Teramae, Mark. “Strategic Culture in Russia-Ukraine Relations.” In Strategic Culture in Russia’s Neighborhood, edited by Katalin Miklossy and Hanna Smith, 1st ed., 211–28. United States: Lexington Books, 2019.

Tesón, Fernando R. “The Liberal Case for Humanitarian Intervention.” In Humanitarian Intervention: Ethical, Legal and Political Dilemmas, edited by J. L. Holzgrefe and Robert O. Keohane, 93–129. Cambridge: Cambridge University Press, 2003. https://doi.org/10.1017/CBO9780511494000.004.

Thayer, Bradley A. “Bringing in Darwin: Evolutionary Theory, Realism, and International Politics.” International Security 25, no. 2 (October 2000): 124–51. https://doi.org/10.1162/016228800560471.

Thelen, Kathleen. “Varieties of Labor Politics In the Developed Democracies.” In Varieties of Capitalism: The Institutional Foundations of Comparative Advantage, edited by Peter A. Hall and David W. Soskice, 71–103. Oxford [England] ; New York: Oxford University Press, 2001.

Theocharis, Yannis, and Jan W. Van Deth. “The Curious Case of Digitally Networked Participation Conceptualizing and Measuring Digitally Enabled Political Participation.” SSRN Electronic Journal, 2015. https://doi.org/10.2139/ssrn.2657082.

Thomas, Scott M. “Taking Religious and Cultural Pluralism Seriously: The Global Resurgence of Religion and the Transformation of International Society.” Millennium: Journal of International Studies 29, no. 3 (December 2000): 815–41. https://doi.org/10.1177/03058298000290030401.

Tickner, J. Ann. “You Just Don’t Understand: Troubled Engagements Between Feminists and IR Theorists.” International Studies Quarterly 41, no. 4 (December 1997): 611–32. https://doi.org/10.1111/1468-2478.00060.

Tickner, J. Ann, and Laura Sjoberg. “Feminism.” In International Relations Theories: Discipline and Diversity, edited by Timothy Dunne, Milja Kurki, and Steve Smith, Third edition., 205–22. Oxford: Oxford University Press, 2013.

Timo Weishaupt, J. “Germany after a Decade of Social Democrats in Government: The End of the Continental Model?” German Politics 19, no. 2 (June 2010): 105–22. https://doi.org/10.1080/09644008.2010.481712.

Tocqueville, Alexis de. Democracy in America. Edited by J. P. Mayer. Translated by George Lawrence. Harper Perennial Modern Classics edition. New York: Harper Perennial Modern Classics, 2006.

Tōgō, Kazuhiko. “The Assertive Conservative Right in Japan: Their Formation and Perspective.” SAIS Review 30, no. 1 (2010): 77–89. https://doi.org/10.1353/sais.0.0078.

Toje, Asle. America, the EU and Strategic Culture: Renegotiating the Transatlantic Bargain. Contemporary Security Studies. London ; Routledge, 2008. https://doi.org/10.4324/9780203929704.

Tomz, Michael. “Domestic Audience Costs in International Relations: An Experimental Approach.” International Organization 61, no. 4 (2007): 821–40. https://doi.org/10.1017/S0020818307070282.

Trachtman, Joel P., and George Norman. “The Customary International Law Game.” American Journal of International Law 99, no. 3 (July 2005): 541–80. https://doi.org/10.2307/1602291.

Trubek, David M., M. Patrick Cottrell, and Mark Thomas Nance. “‘Soft Law,’ ‘Hard Law,’ and European Integration: Toward a Theory of Hybridity.” SSRN Electronic Journal, 2005. https://doi.org/10.2139/ssrn.855447.

Trubek, David M., and James S. Mosher. “New Governance, Employment Policy, and the European Social Model.” In Governing Work and Welfare in a New Economy: European and American Experiments, edited by Jonathan Zeitlin and David M. Trubek, 33–58. Oxford University Press, 2003.

Tsingou, Eleni. “Regulatory Reactions to the Global Credit Crisis: Analyzing a Policy Community Under Stress.” In Global Finance in Crisis: The Politics of International Regulatory Change, edited by Eric Helleiner, Stefano Pagliari, and Hubert Zimmermann, 21–36. Routledge, 2010.

Uhlaner, Carole J. “Relational Goods and Resolving the Paradox of Political Participation.” RECERCA. Revista de Pensament i Anàlisi, no. 14 (2014): 47–72. https://doi.org/10.6035/Recerca.2014.14.3.

Uhlaner, Carole Jean. “‘Relational Goods’ and Participation: Incorporating Sociability into a Theory of Rational Action.” Public Choice 62, no. 3 (September 1989): 253–85. https://doi.org/10.1007/BF02337745.

United Nations Genocide Convention, 1948.

Utter, R.F., and D.C. Lundsgaard. “Judicial Review in the New Nations of Central and Eastern Europe: Some Thoughts from a Comparative Perspective.” Ohio State Law Journal 54, no. 3 (1993): 559–606.

Valenzuela, Sebastián, Arturo Arriagada, and Andrés Scherman. “The Social Media Basis of Youth Protest Behavior: The Case of Chile.” Journal of Communication 62, no. 2 (2012): 299–314. https://doi.org/10.1111/j.1460-2466.2012.01635.x.

Van Evera, Stephen. Guide to Methods for Students of Political Science. Cornell University Press, 2015.

Verdun, Amy, and Martin Heipertz, eds. “Conclusion: The Past, Present and Future of the SGP and Implications for European Integration Theory.” In Ruling Europe: The Politics of the Stability and Growth Pact, 196–204. Cambridge: Cambridge University Press, 2010. https://doi.org/10.1017/CBO9780511750380.012.

———, eds. “The Politics of the Stability and Growth Pact.” In Ruling Europe: The Politics of the Stability and Growth Pact, 1–16. Cambridge: Cambridge University Press, 2010. https://doi.org/10.1017/CBO9780511750380.003.

———, eds. “The SGP in Times of Financial Turbulence and Economic Crisis.” In Ruling Europe: The Politics of the Stability and Growth Pact, 174–95. Cambridge: Cambridge University Press, 2010. https://doi.org/10.1017/CBO9780511750380.011.

Vermeersch, Peter. “Ethnic Minority Identity and Movement Politics: The Case of the Roma in the Czech Republic and Slovakia.” Ethnic and Racial Studies 26, no. 5 (September 2003): 879–901. https://doi.org/10.1080/0141987032000109078.

Verveer, Melanne. “Why Women Are a Foreign Policy Issue.” Foreign Policy (blog), April 23, 2012. https://foreignpolicy.com/2012/04/23/why-women-are-a-foreign-policy-issue/.

Veseth, Michael. Globaloney 2.0 : The Crash of 2008 and the Future of Globalization. Globalization; Globalization (Lanham, Md.), Book, Whole. Lanham, Md.: Rowman & Littlefield, 2010. http://www2.lib.ncsu.edu/catalog/record/DUKE004280517.

Vetterlein, Antje. “Economic Growth, Poverty Reduction, and the Role of Social Policies: The Evolution of the World Bank’s Social Development Approach.” Global Governance 13, no. 4 (2007): 513–33. https://doi.org/10.1163/19426720-01304006.

Victor D. Cha. “Complex Patchworks: U.S. Alliances as Part of Asia’s Regional Architecture.” Asia Policy 11, no. 1 (2011): 27–50. https://doi.org/10.1353/asp.2011.0004.

Vincent, Etienne, Philip Eles, and Boris Vasiliev. “Opinion Polling in Support of Counterinsurgency.” The Cornwallis Group XIV: Analysis of Societal Conflict and Counter-Insurgency, 2010, 104–125.

Viotti, Paul R., and Mark V. Kauppi. International Relations Theory. 5th ed. Boston: Longman, 2012.

Vis, Barbara. “Governments and Unpopular Social Policy Reform: Biting the Bullet or Steering Clear?” European Journal of Political Research 48, no. 1 (January 2009): 31–57. https://doi.org/10.1111/j.1475-6765.2008.00783.x.

Vreeland, James Raymond. “What Is the IMF?” In The International Monetary Fund (IMF): Politics of Conditional Lending, 5–36. Routledge, 2006.

Wagnerová, Eliška. “Position of Judges in the Czech Republic.” In Systems of Justice in Transition: Central European Experiences Since 1989, edited by Jiří Přibáň, Pauline Isobel Roberts, and James Young, 165–79. Burlington, VT: Ashgate, 2003.

Wahl, Peter. “Between Eurotopia and Nationalism: A Third Way for the Future of the EU.” Globalizations 14, no. 1 (January 2, 2017): 157–63. https://doi.org/10.1080/14747731.2016.1228787.

Wallace, Ruth A. “Emile Durkheim and the Civil Religion Concept.” Review of Religious Research 18, no. 3 (1977): 287–290. https://doi.org/10.2307/3510218.

Wallander, Celeste A. “Institutional Assets and Adaptability: NATO After the Cold War.” International Organization 54, no. 4 (2000): 705–35. https://doi.org/10.1162/002081800551343.

Wallensteen, Peter, and Patrik Johansson. “Security Council Decisions in Perspective.” In The UN Security Council: From the Cold War to the 21st Century, edited by David Malone, 17–33. Lynne Rienner Publishers, 2004.

Warburg, Margit. “Transnational Civil Religion: The Fourth of July in Denmark.” In Holy Nations and Global Identities, edited by Brian Jacobsen, Margit Warburg, and Annika Hvithamar, 271–93. Brill, 2009. https://doi.org/10.1163/ej.9789004178281.i-310.41.

Weaver, Catherine. “The World’s Bank and the Bank’s World.” Global Governance 13, no. 4 (2007): 493–512. https://doi.org/10.1163/19426720-01304005.

Weeden, Brian. “Overview of the Legal and Policy Challenges of Orbital Debris Removal.” Space Policy 27, no. 1 (2011): 38–43. https://doi.org/10.1016/j.spacepol.2010.12.019.

Weeks, Jessica L. “Autocratic Audience Costs: Regime Type and Signaling Resolve.” International Organization 62, no. 01 (January 2008). https://doi.org/10.1017/S0020818308080028.

Weiss, Jessica Chen. “Authoritarian Signaling, Mass Audiences, and Nationalist Protest in China.” International Organization 67, no. 1 (January 2013): 1–35. https://doi.org/10.1017/S0020818312000380.

Werner, Suzanne, and Amy Yuen. “Making and Keeping Peace.” International Organization 59, no. 2 (2005): 261–92.

Widmaier, Wesley W., Mark Blyth, and Leonard Seabrooke. “Exogenous Shocks or Endogenous Constructions? The Meanings of Wars and Crises.” International Studies Quarterly 51, no. 4 (December 1, 2007): 747–59. https://doi.org/10.1111/j.1468-2478.2007.00474.x.

Wilkinson, Steven. Votes and Violence: Electoral Competition and Ethnic Riots in India. Cambridge Studies in Comparative Politics. Cambridge ; New York: Cambridge University Press, 2004.

“Wilkinson_2004_Votes and Violence.Pdf,” n.d.

Williamson, John. “What Washington Means by Policy Reform.” In Latin American Adjustment: How Much Has Happened?, 7–20. Institute for International Economics, 1990.

Williamson, Ray A. “Assuring the Sustainability of Space Activities.” Space Policy 28, no. 3 (2012): 154–60. https://doi.org/10.1016/j.spacepol.2012.06.010.

Wittman, Donald. “How a War Ends: A Rational Model Approach.” Journal of Conflict Resolution 23, no. 4 (December 1979): 743–63. https://doi.org/10.1177/002200277902300408.

Wolchik, Sharon L. “The Czech and Slovak Republics: Two Paths to the Same Destination.” In Central and East European Politics, edited by and Jane L. CurryCentral, 191–214. Lanham, MA: Rowman & Littlefield Publishers, Inc, 2008.

———. “The Politics of Ethnicity in Post-Communist Czechoslovakia.” East European Politics and Societies: And Cultures 8, no. 1 (December 1993): 153–88. https://doi.org/10.1177/0888325494008001006.

Wolff, Stefan. “Introduction: From Sunningdale to Belfast, 1973-98.” In Peace at Last?: The Impact of the Good Friday Agreement on Northern Ireland, edited by Jörg Neuheiser and Stefan Wolff. Berghahn Books, 2004.

Woodberry, Robert D. “The Missionary Roots of Liberal Democracy.” American Political Science Review 106, no. 2 (May 2012): 244–74. https://doi.org/10.1017/S0003055412000093.

“Woodberry_2012_The Missionary Roots of Liberal Democracy.Pdf,” n.d.

Woods, Ngaire. “Holding Intergovernmental Institutions to Account.” Ethics & International Affairs 17, no. 1 (2003): 69–80. https://doi.org/10.1111/j.1747-7093.2003.tb00419.x.

———. “Making the IMF and the World Bank More Accountable.” International Affairs 77, no. 1 (2001): 83–100. https://doi.org/10.1111/1468-2346.00179.

Wright, Thomas. “Toward Effective Multilateralism: Why Bigger May Not Be Better.” The Washington Quarterly 32, no. 3 (2009): 163–80. https://doi.org/10.1080/01636600903035753.

X. “The Sources of Soviet Conduct.” Foreign Affairs 65, no. 4 (1987): 852–68. https://doi.org/10.2307/20043098.

Yarhi-Milo, Keren. “In the Eye of the Beholder: How Leaders and Intelligence Communities Assess the Intentions of Adversaries.” International Security 38, no. 1 (July 2013): 7–51. https://doi.org/10.1162/ISEC_a_00128.

Zaller, John, and Stanley Feldman. “A Simple Theory of the Survey Response: Answering Questions versus Revealing Preferences.” American Journal of Political Science 36, no. 3 (1992): 579–616. https://doi.org/10.2307/2111583.

Ziblatt, Daniel. Conservative Parties and the Birth of Democracy. Cambridge Studies in Comparative Politics. Cambridge New York Port Melbourne Delhi Singapore: Cambridge University Press, 2017.

“Ziblatt_2017_Conservative Parties and the Birth of Democracy.Pdf,” n.d.

Zürn, Michael. “Democratic Governance Beyond the Nation-State: The EU and Other International Institutions.” European Journal of International Relations 6, no. 2 (2000): 183–221. https://doi.org/10.1177/1354066100006002002.

Zwolski, Kamil. “The EU as an International Security Actor after Lisbon: Finally a Green Light for a Holistic Approach?” Cooperation and Conflict 47, no. 1 (2012): 68–87. https://doi.org/10.1177/0010836711433126.

Zysk, Katarzyna. “Russia’s Naval Ambitions: Driving Forces and Constraints.” In Twenty-First Century Seapower: Cooperation and Conflict at Sea, edited by Peter Dutton, Robert S. Ross, and Øystein Tunsjø, 112–35. Cass Series: Naval Policy and History 49. London ; New York: Routledge, 2012.
