---
title: "American Government — Fall 2018"
date: "2025-02-03"
---

## American Government Pol Sci 21A

Fall 2018

Archived from https://sites.google.com/uci.edu/ 2022-09-06

Welcome to Pol Sci 21a

Policies and information about discussion sections are subject to change. Written notice (e.g. email) will be given prior to any changes. If a section policy conflicts with the class syllabus, the class syllabus is the final authority.

Office Hours: SST 665 Wednesday 11:00-12:00pm starting Week 2

Email: plove (at) uci.edu

[Section Materials](../../teaching/section-materials-f18.html)

Electronics Use During Section

  * You may use your laptop or tablet during section for class-related activities (e.g. no messaging). For example, you can reference the e-Textbook.

  * Mobile phone use is prohibited.

Attendance and Participation:

  * Discussion section attendance is mandatory (except when notified in writing otherwise).

  * Both your presence and your participation in section will be factored into your grade (10% of your overall grade in the course; see class syllabus).

  * Please be respectful of others viewpoints and beliefs in class.

  * If you are absent from discussion, you will not receive credit for that day.

  * You cannot make up attendance by attending a section with another TA.

  * I will drop your lowest participation score. Effectively, you can miss one section without consequence to your grade. You will still need to get notes from your classmates.

  * If you know you will not be able to attend section, please email me ahead of time and we can arrange for you to attend another section during the same week. If no time works in that week, then you can count that absence towards your dropped participation score.

  * In the event that more absences occur due to unforeseen circumstances (illness, emergencies, etc.), please contact me as soon as possible to make arrangements for grading. Please provide documentary evidence for your extenuating circumstances.

  * If you move sections, especially if you move to another TA during the drop/add period, please email me to let me know to ensure your participation is recorded.

Weekly Questions

  * Please make sure to add to the top of your questions

    * Your name

    * ID number

    * Section number or section time (e.g. Wed 10 am) to the top of your questions.

  * Submissions need to be typed not handwritten.

  * Tips:

    * Bold or underline key words and phrases.

    * Keep your answers concise.

    * Add the question text above your answers.

Exams:

  * Please note I do not return emails the night before an exam. Please send any questions before 4:00 pm the day prior to the exam.

    * I can answer specific questions about the course material or general logistics questions via email. I am unable to provide comprehensive review material via email. I will be able to provide more in-depth answers during my office hours and in section.

  * I will be responsible for grading your exams.

  * There is no planned curve for the exams.

  * Ensure that your student ID are on your exams when you return them.

  * There is no study guide planned for release. However, exam review will take place during discussion sections prior to exams. Please come prepared with questions.

  * If you are unfamiliar with writing for political science, please take a look at the [Exam Tips]() page on my section's site.

  * Please clearly label all sections and subsections of questions. For example, if there are parts a, b, and c. Label your answers with "a", "b", and "c".

  * When answering questions, please be direct, clear, and concise.

  * Answers to questions should not be based on your personal opinion. Use empirical evidence from the course, course materials, etc. to advance your argument.

  * Focus on the content. For example, in long-form essays, formatting such as introductions and conclusions are unnecessary.

  * Non-answers and blank answers receive little to no credit.

    * Example of non-answer

      * Question ID: Budget Reconciliation Bill

      * Answer: A bill that reconciles the budget.
