---
title: "Voting and Political Manipulation — Spring 2021"
date: "2025-02-03"
---

## Voting and Political Manipulation Sections 1, 14, and 15

### VPM Supplemental Resources

[VPM and Voting Theory Tips](../../resources/vpm-and-voting-theory.html)

### Office Hour

  * Office Hours: Fridays 10:00-10:50 am PDT via Zoom (Link is available on Canvas)

  * Please email me at least a day in advance that you are coming to the Zoom meeting.

  * However, the best way to find me is by email at plove (at) uci (dot) edu

### What to Expect in Section?

  * Please make sure to watch the lectures prior to coming to section. These sessions are a place to ask questions and practice some of the ideas from the lectures.

  * Sections are only a complement to the lecture material.

  * Disclaimer: There may be conflicting information with class texts or lecture. For our purposes and for evaluation, we will use whatever information, vocabulary, or methods the professor has chosen.

  * Please respect your fellow classmates in our shared setting. We want to make our time together as productive as possible.

### Attendance

  * Note that I will not be recording our live sessions.

  * If you cannot attend your normally scheduled section, you can attend any of the other 14 sections offered. My sections are 1, 14, and 15.

  * Attendance is optional, and it will not be recorded.

  * However, attendance is recommended.

  * Please make sure to review the “Intuitions” PDF posted for each module even if you are unable to attend any section for the week.
