---
title: "Courses"
date: "2026-09-18"
description: "Courses taught by Paul Max Love III at NYU Abu Dhabi and as a teaching assistant at UC Irvine."
schema-type: course-list
course-list:
  - teaching/courses/2026-fall-is.html
  - teaching/courses/2026-spring-da.html
  - teaching/courses/2026-jterm-politics.html
  - teaching/courses/2025-2026-capstone.html
  - teaching/courses/2025-fall-da.html
  - teaching/courses/2025-spring-da.html
  - teaching/courses/2025-spring-stats.html
  - teaching/courses/2024-fall-stats.html
  - teaching/courses/2024-summer-boundaries.html
  - teaching/courses/2024-spring-stats.html
  - teaching/courses/2023-fall-stats.html
---

## NYU Abu Dhabi

[International Security](2026-fall-is.html), Fall 2026

[Data Analysis: Political Science](2026-spring-da.html), Spring 2026

[J-Term Politics](2026-jterm-politics.html), 2026

[Capstone Seminar](2025-2026-capstone.html), 2025–2026

[Data Analysis: Political Science](2025-fall-da.html), Fall 2025

[Data Analysis](2025-spring-da.html), Spring 2025

[Statistics for Social and Behavioral Sciences](2025-spring-stats.html), Spring 2025

[Statistics for Social and Behavioral Sciences](2024-fall-stats.html), Fall 2024

[Boundaries](2024-summer-boundaries.html), Summer 2024

[Statistics for Social and Behavioral Sciences](2024-spring-stats.html), Spring 2024

Negotiation and Consensus Building (Sections 1, 2, and 3), Spring 2024

Quantitative Data Analysis, Fall 2023

[Statistics for Social and Behavioral Sciences](2023-fall-stats.html), Fall 2023

Boundaries, Summer 2023

## Teaching Assistant, UC Irvine

[Voting and Political Manipulation](2021-spring-vpm.html), Spring 2021 (Virtual)

American Government, Fall 2020 (Virtual)

Voting and Political Manipulation, Spring 2020 (Virtual)

American Political Thought, Winter 2020

American Foreign Policy, Fall 2019

Game Theory and Politics I, Spring 2019

Voting and Political Manipulation, Winter 2019

[American Government](2018-fall-american-government.html), Fall 2018

American Government, Spring 2018 ([course site](https://sites.google.com/uci.edu/pol21as18plove/home))

American Government, Winter 2018

Voting and Political Manipulation, Fall 2017

Macropolitics, Spring 2016

American Public Policy, Winter 2016

International Political Economy, Fall 2015

## Teaching Assistant, North Carolina State University

International Relations Theory, Spring 2012

International Relations Theory, Fall 2011
