---
title: "Section Materials — Fall 2018"
date: "2025-02-03"
---

## Exam Tips

General Guidelines for Writing Blue Book Exams and Political Science Writing

[Writing PolSci Essay Georgetown University](http://faculty.georgetown.edu/kingch/Writing_PolSci_Essay.htm)

[Writing Tips « Writers Workshop: Writer Resources « The Center for Writing Studies, Illinois](https://web.archive.org/web/20200813150223/https://cws.illinois.edu/workshop/writers/tips/inclassessay/)

### Link to Textbook Site

[https://openstax.org/details/books/american-government](https://openstax.org/details/books/american-government)

## Week 2

Prisoners Dilemma Video: Golden Balls

[https://www.youtube.com/watch?v=S0qjK3TWZE8](https://www.youtube.com/watch?v=S0qjK3TWZE8)

Tragedy of the Commons (TED Ed)

[https://youtu.be/CxC161GvMPc](https://youtu.be/CxC161GvMPc)

## Week 3

California Voter Guide

[http://voterguide.sos.ca.gov/](http://voterguide.sos.ca.gov/)

**Correction**

Canada is an example of a federal system. It is not a unitary government.

Supplemental resource on Canada

[https://www.canada.ca/en/intergovernmental-affairs/services/federation/federalism-canada.html](https://web.archive.org/web/20181027002548/https://www.canada.ca/en/intergovernmental-affairs/services/federation/federalism-canada.html)

## Week 4

Magna Carta

[https://youtu.be/7xo4tUMdAMw](https://youtu.be/7xo4tUMdAMw)

Incorporation Doctrine

[https://www.law.cornell.edu/wex/incorporation_doctrine](https://www.law.cornell.edu/wex/incorporation_doctrine)

## Week 5

Electoral College

[https://youtu.be/OUS9mM8Xbbw](https://youtu.be/OUS9mM8Xbbw)

Issues with the Electoral College

[https://youtu.be/7wC42HgLA4k](https://youtu.be/7wC42HgLA4k)

Gerrymandering

[https://youtu.be/Mky11UJb9AY](https://youtu.be/Mky11UJb9AY)

Political Ad (Influence of constituency over party)

[https://youtu.be/xIJORBRpOPM](https://youtu.be/xIJORBRpOPM)

## Week 6

Key Terms (Excerpted from Professor Goggin's Lecture Slides)

1\. Coordination problem

2\. Free-rider problem

3\. Tragedy of the commons

4\. Prisoners’ dilemma

5\. Institution

6\. Transaction cost

7\. Conformity cost

8\. Private good

9\. Common good

10\. Toll good

11\. Public good

12\. Republic

13\. (direct) democracy

14\. Articles of Confederation

15\. Shay’s rebellion

16\. 3/5 Compromise

17\. Commerce clause

18\. Supremacy clause

19\. Virginia plan

20\. New Jersey Plan

21\. Logroll

22\. Faction

23\. Dual federalism

24\. Cooperative federalism

25\. New federalism

26\. Vertical separation of powers

27\. Horizontal separation of powers

28\. Race to the bottom

29\. Block grants

30\. Categorical grants (matching)

31\. 10th amendment

32\. Civil rights

33\. Civil liberties

34\. Suffrage

35\. Jim Crow laws

36\. de facto

37\. de jure

38\. Treaty of Guadalupe Hidalgo

39\. Initiative & Referendum

40\. Duverger’s Law

41\. patronage

42\. McGovern-Fraser Commission

43\. primary election

44\. superdelgates

45\. Invisible primary

46\. necessary and proper clause

47\. credit claiming

48\. position taking

49\. gerrymandering

50\. pork barrel legislation

51\. filibuster

52\. cloture

53\. closed rule

54\. Hastert rule

55\. unanimous consent agreements

56\. take care clause

57\. electoral college

58\. line-item veto

59\. divided government

60\. executive order

61\. going public

62\. bureaucracy

63\. spoils system

64\. Pendleton Act (1883)

65\. Cabinet agency

66\. Independent Executive Agency

67\. Independent Regulatory Commission

68\. signing statements

69\. regulatory review

70\. police patrols v. fire alarms

71\. legislative veto

72\. limitation rider

73\. Marbury v. Madison (1803)

74\. judicial review

75\. McCulloch v. Maryland (1819)

76\. stare decisis

77\. Rule of Four

78\. writ of certiorari

79\. Solicitor general

80\. Original vs. appellate jurisdiction

## Week 7

Supreme Court Information

[https://www.oyez.org](https://www.oyez.org)

## Week 8

Thanksgiving Week

## Week 9

Canceled

## Week 10

The Influence of Super PACs on the 2012 Elections

[https://youtu.be/JH7xfjbostk](https://youtu.be/JH7xfjbostk)

Media Ownership (very in-depth)

[https://youtu.be/DvSTlxJsKzE](https://youtu.be/DvSTlxJsKzE)

Why do so few Americans vote?

[https://youtu.be/FXnn1uG8i2k](https://youtu.be/FXnn1uG8i2k)

Pros and cons of public opinion polls - Jason Robert Jaffe

[https://youtu.be/ubR8rEgSZSU](https://youtu.be/ubR8rEgSZSU)

Final Exam Terms (Excerpted from Professor Goggin's Lecture Slides)

1 pluralism

2 insider tactics

3 outsider tactics

4 selective incentives

5 grassroots lobbying

6 astroturf (lobbying)

7 Issue networks

8 Iron triangles

9 belief

10 emotion

11 values

12 attitude

13 opinion

14 focus group

15 nonscientific polling

16 scientific polling

17 coverage error

18 margin of error

19 nonresponse bias

20 social desirability bias

21 socialization

22 cue-taking

23 Magic of aggregation

24 Ideological polarization

25 sorting

26 affective polarization

27 belief polarization

28 heuristic

29 rational turnout model

30 four P's of electoral choice

31 four campaign goals

32 PAC

33 Super-PAC

34 initiatives/referenda

35 penny press

36 yellow journalism

37 muckraking

38 prior restraint

39 libel

40 slander

41 persuasion

42 agenda-setting

43 priming

44 framing

45 trial balloon

46 continuing resolution

47 policy window

48 budget authority

49 budget outlays

50 tax expenditures

51 War Powers Resolution (1973)

52 AUMF

53 rally-around-the-flag effect

54 status quo bias
